/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class gde_device_igc_IGCDLL */

#ifndef _Included_gde_device_igc_IGCDLL
#define _Included_gde_device_igc_IGCDLL
#ifdef __cplusplus
extern "C" {
#endif

/*
 * Class:     gde_device_igc_IGCDLL
 * Method:    validateLog
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_gde_device_igc_IGCDLL_validateLog
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
