//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1.5-b01-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.12.15 at 04:01:10 PM MEZ 
//

package gde.histocache;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;

import gde.GDE;

/**
 * holds either trails for measurements and
 * 				settlements or score labels for scores
 * 			
 * 
 * <p>Java class for entryPoints complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="entryPoints">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="point" type="{}point" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="id" use="required" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="text" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "entryPoints", propOrder = {
    "point"
})
public class EntryPoints {

    protected List<Point> point;
	@XmlAttribute(required = true)
    protected int id;
  @XmlAttribute(required = true)
  protected String text;

	public EntryPoints() {
		// for marshalling purposes only
	}

	/**
	 * @param name
	 * @param id
	 */
	public EntryPoints(int id, String text) {
		this.id = id;
		this.text = text;
	}

	public void addPoint(int id, String name, int value) {
		Point point = new Point();
		point.setId(id);
		point.setName(name);
		point.setValue(value);
		this.getPoints().add(point);
	}

	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append(text).append(GDE.STRING_BLANK_COLON_BLANK).append(id).append(GDE.STRING_BLANK_COLON_BLANK);
		if (point != null) {
			for (Point dataPoint : point) {
				sb.append(dataPoint.getName().toLowerCase()).append(GDE.STRING_EQUAL).append(dataPoint.getValue()).append(GDE.STRING_BLANK);
			}
		}
		return sb.toString();
	}

	/**
	 * Gets the value of the point property.
	 * 
	 * <p>
	 * This accessor method returns a reference to the live list,
	 * not a snapshot. Therefore any modification you make to the
	 * returned list will be present inside the JAXB object.
	 * This is why there is not a <CODE>set</CODE> method for the point property.
	 * 
	 * <p>
	 * For example, to add a new item, do as follows:
	 * <pre>
	 *    getPoint().add(newItem);
	 * </pre>
	 * 
	 * 
	 * <p>
	 * Objects of the following type(s) are allowed in the list
	 * {@link Point }
	 * 
	 * 
	 */
    public List<Point> getPoints() {
        if (point == null) {
            point = new ArrayList<Point>();
		}
        return this.point;
	}

	/**
     * Gets the value of the id property.
	 *     
	 */
    public int getId() {
        return id;
	}

	/**
     * Sets the value of the id property.
	 * 
	 */
    public void setId(int value) {
        this.id = value;
	}

	/**
     * Gets the value of the text property.
     * 
     * @return
     *     possible object is
     *     {@link String }
	 * 
	 */
    public String getText() {
        return text;
	}

	/**
     * Sets the value of the text property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
	 * 
	 */
    public void setText(String value) {
        this.text = value;
	}

}
