//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1.5-b01-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.11.18 at 05:52:18 AM MEZ 
//

package gde.histocache;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;

import gde.GDE;

/**
 * <p>Java class for entryPoints complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="entryPoints">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}point" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="name" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="id" use="required" type="{http://www.w3.org/2001/XMLSchema}int" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "entryPoints", propOrder = { "points" })
public class EntryPoints {

	protected List<Point>	points;
	@XmlAttribute(required = true)
	protected String			name;
	@XmlAttribute(required = true)
	protected int					id;

	public EntryPoints() {
		// for marshalling purposes only
	}

	/**
	 * @param name
	 * @param id
	 */
	public EntryPoints(String name, int id) {
		this.name = name;
		this.id = id;
	}

	public void addPoint(String name, int id, int value) {
		Point point = new Point();
		point.setName(name);
		point.setId(id);
		point.setValue(value);
		this.getPoints().add(point);
	}

	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append(name).append(GDE.STRING_BLANK_COLON_BLANK).append(id).append(GDE.STRING_BLANK_COLON_BLANK);
		if (points != null) {
			for (Point point : points) {
				sb.append(point.getName().toLowerCase()).append(GDE.STRING_EQUAL).append(point.getValue()).append(GDE.STRING_BLANK);
			}
		}
		return sb.toString();
	}

	/**
	 * Gets the value of the point property.
	 * 
	 * <p>
	 * This accessor method returns a reference to the live list,
	 * not a snapshot. Therefore any modification you make to the
	 * returned list will be present inside the JAXB object.
	 * This is why there is not a <CODE>set</CODE> method for the point property.
	 * 
	 * <p>
	 * For example, to add a new item, do as follows:
	 * <pre>
	 *    getPoint().add(newItem);
	 * </pre>
	 * 
	 * 
	 * <p>
	 * Objects of the following type(s) are allowed in the list
	 * {@link Point }
	 * 
	 * 
	 */
	public List<Point> getPoints() {
		if (points == null) {
			points = new ArrayList<Point>();
		}
		return this.points;
	}

	/**
	 * Gets the value of the name property.
	 * 
	 * @return
	 *     possible object is
	 *     {@link String }
	 *     
	 */
	public String getName() {
		return name;
	}

	/**
	 * Sets the value of the name property.
	 * 
	 * @param value
	 *     allowed object is
	 *     {@link String }
	 *     
	 */
	public void setName(String value) {
		this.name = value;
	}

	/**
	 * Gets the value of the id property.
	 * 
	 */
	public int getId() {
		return id;
	}

	/**
	 * Sets the value of the id property.
	 * 
	 */
	public void setId(int value) {
		this.id = value;
	}

}
