//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1.5-b01-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.12.14 at 04:26:28 PM MEZ 
//
/**************************************************************************************
  	This file is part of GNU DataExplorer.

    GNU DataExplorer is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    DataExplorer is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with GNU DataExplorer.  If not, see <http://www.gnu.org/licenses/>.
    
    Copyright (c) 2017 Thomas Eickert
****************************************************************************************/

package gde.histocache;

import java.io.File;
import java.io.FileInputStream;
import java.io.IOException;
import java.io.InputStream;
import java.io.OutputStream;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.security.MessageDigest;
import java.security.NoSuchAlgorithmException;
import java.util.ArrayList;
import java.util.EnumSet;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map.Entry;
import java.util.Optional;
import java.util.TreeMap;
import java.util.logging.Logger;

import javax.xml.XMLConstants;
import javax.xml.bind.JAXBContext;
import javax.xml.bind.JAXBException;
import javax.xml.bind.Marshaller;
import javax.xml.bind.Unmarshaller;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlTransient;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.XmlAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import javax.xml.validation.SchemaFactory;

import gde.GDE;
import gde.config.Settings;
import gde.data.HistoSettlement;
import gde.data.HistoTransitions;
import gde.data.Record;
import gde.data.RecordSet;
import gde.device.ChannelPropertyType;
import gde.device.ChannelPropertyTypes;
import gde.device.IDevice;
import gde.device.MeasurementType;
import gde.device.ScoreLabelTypes;
import gde.device.SettlementType;
import gde.device.StatisticsType;
import gde.device.TrailTypes;
import gde.device.TransitionAmountType;
import gde.device.TransitionCalculusType;
import gde.device.TransitionFigureType;
import gde.exception.DataInconsitsentException;
import gde.exception.NotSupportedFileFormatException;
import gde.io.HistoOsdReaderWriter;
import gde.log.Level;
import gde.ui.DataExplorer;
import gde.utils.Quantile;
import gde.utils.Quantile.Fixings;
import gde.utils.StringHelper;

/**
 * aggregated history recordset data related to measurements, settlements and
 * 				scores.
 * 				No localization required.
 * 			
 * 
 * <p>Java class for histoVault complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="histoVault">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="vaultName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="vaultDirectory" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="vaultCreated_ms" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *         &lt;element name="vaultDataExplorerVersion" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="vaultDeviceKey" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="vaultDeviceName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="vaultChannelNumber" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="vaultObjectKey" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="vaultSamplingTimespan_ms" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *         &lt;element name="logFilePath" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="logFileLastModified" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *         &lt;element name="logFileLength" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *         &lt;element name="logObjectDirectory" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="logFileVersion" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="logRecordSetSize" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="logRecordSetOrdinal" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="logRecordsetBaseName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="logDeviceName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="logChannelNumber" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="logObjectKey" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="logStartTimestamp_ms" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *         &lt;element name="measurements" type="{}entryCompartments"/>
 *         &lt;element name="settlements" type="{}entryCompartments"/>
 *         &lt;element name="scores" type="{}entryPoints"/>
 *        &lt;/sequence>
 *      &lt;/restriction>
 *    &lt;/complexContent>
 *  &lt;/complexType>
 * </pre>
 * 
 * 
 */
/**
 * suitable for history persistence and xml serialization.
 * may exist in two stages: 
 *  - truss: does not hold measurement, settlement or score points
 *  - vault: the number of points conform to the device xml for settlements and scores, but only a subset of measurements is required
 * supports creating a truss or accessing a vault without having read the original log file.
 * find the constructors and non-xsd code a good way down for simplified merging with JAXB generated class.  
 * @author Thomas Eickert
 */
@XmlRootElement
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "histoVault", propOrder = { "vaultName", "vaultDirectory", "vaultCreatedMs", "vaultDataExplorerVersion", "vaultDeviceKey", "vaultDeviceName", "vaultChannelNumber", "vaultObjectKey",
		"vaultSamplingTimespanMs", "logFilePath", "logFileLastModified", "logFileLength", "logObjectDirectory", "logFileVersion", "logRecordSetSize", "logRecordSetOrdinal", "logRecordsetBaseName",
		"logDeviceName", "logChannelNumber", "logObjectKey", "logStartTimestampMs", "measurements", "settlements", "scores" })
public class HistoVault {
	final private static String									$CLASS_NAME	= HistoVault.class.getName();
	final private static Logger									log					= Logger.getLogger($CLASS_NAME);

	private static Path													activeDevicePath;																	// criterion for the active device version key cache
	private static String												activeDeviceKey;																	// caches the version key for the active device which is calculated only if the device is changed by the user
	private static long													activeDeviceLastModified_ms;											// caches the version key for the active device which is calculated only if the device is changed by the user
	private static JAXBContext									jaxbContext;
	private static Unmarshaller									jaxbUnmarshaller;
	private static Marshaller										jaxbMarshaller;

	@XmlTransient
	private final DataExplorer									application	= DataExplorer.getInstance();
	@XmlTransient
	private final Settings											settings		= Settings.getInstance();
	@XmlTransient
	private final IDevice												device			= this.application.getActiveDevice();

	@XmlElement(required = true)
	protected String														vaultName;
	@XmlElement(required = true)
	protected String														vaultDirectory;
	@XmlElement(name = "vaultCreated_ms")
	protected long															vaultCreatedMs;
	@XmlElement(required = true)
	protected String														vaultDataExplorerVersion;
	@XmlElement(required = true)
	protected String														vaultDeviceKey;
	@XmlElement(required = true)
	protected String														vaultDeviceName;
	protected int																vaultChannelNumber;
	@XmlElement(required = true)
	protected String														vaultObjectKey;
	@XmlElement(name = "vaultSamplingTimespan_ms")
	protected long															vaultSamplingTimespanMs;
	@XmlElement(required = true)
	protected String														logFilePath;
	protected long															logFileLastModified;
	protected long															logFileLength;
	@XmlElement(required = true)
	protected String														logObjectDirectory;
	protected int																logFileVersion;
	protected int																logRecordSetSize;
	protected int																logRecordSetOrdinal;
	@XmlElement(required = true)
	protected String														logRecordsetBaseName;
	@XmlElement(required = true)
	protected String														logDeviceName;
	protected int																logChannelNumber;
	@XmlElement(required = true)
	protected String														logObjectKey;
	@XmlElement(name = "logStartTimestamp_ms")
	protected long															logStartTimestampMs;
	@XmlElement(required = true)
	@XmlJavaTypeAdapter(CompartmentsTypeAdapter.class)
	protected HashMap<Integer, CompartmentType>	measurements;
	@XmlElement(required = true)
	@XmlJavaTypeAdapter(CompartmentsTypeAdapter.class)
	protected HashMap<Integer, CompartmentType>	settlements;
	@XmlElement(required = true)
	@XmlJavaTypeAdapter(PointsTypeAdapter.class)
	protected HashMap<Integer, PointType>				scores;

	/**
	   * Gets the value of the vaultName property.
	   * 
	   * @return
	   *     possible object is
	   *     {@link String }
	   *     
	   */
	public String getVaultName() {
		return vaultName;
	}

	/**
	   * Sets the value of the vaultName property.
	   * 
	   * @param value
	   *     allowed object is
	   *     {@link String }
	   *     
	   */
	public void setVaultName(String value) {
		this.vaultName = value;
	}

	/**
	* Gets the value of the vaultDirectory property.
	* 
	* @return
	*     possible object is
	*     {@link String }
	*     
	*/
	public String getVaultDirectory() {
		return vaultDirectory;
	}

	/**
	 * Sets the value of the vaultDirectory property.
	 * 
	 * @param value
	 *     allowed object is
	 *     {@link String }
	 *     
	 */
	public void setVaultDirectory(String value) {
		this.vaultDirectory = value;
	}

	/**
	 * Gets the value of the vaultCreatedMs property.
	 * 
	 */
	public long getVaultCreated_ms() {
		return vaultCreatedMs;
	}

	/**
	   * Sets the value of the vaultCreatedMs property.
	   * 
	   */
	public void setVaultCreated_Ms(long value) {
		this.vaultCreatedMs = value;
	}

	/**
	 * Gets the value of the vaultDataExplorerVersion property.
	*     
	 * @return
	 *     possible object is
	 *     {@link String }
	 *     
	*/
	public String getVaultDataExplorerVersion() {
		return vaultDataExplorerVersion;
	}

	/**
	 * Sets the value of the vaultDataExplorerVersion property.
	 * 
	 * @param value
	 *     allowed object is
	 *     {@link String }
	 *     
	 */
	public void setVaultDataExplorerVersion(String value) {
		this.vaultDataExplorerVersion = value;
	}

	/**
	   * Gets the value of the vaultDeviceKey property.
	 * 
	 * @return
	 *     possible object is
	   *     {@link String }
	 *     
	 */
	public String getVaultDeviceKey() {
		return vaultDeviceKey;
	}

	/**
	 * Sets the value of the vaultDeviceKey property.
	 * 
	 * @param value
	 *     allowed object is
	 *     {@link String }
	 *     
	 */
	public void setVaultDeviceKey(String value) {
		this.vaultDeviceKey = value;
	}

	/**
	   * Gets the value of the vaultDeviceName property.
	   * 
	   * @return
	   *     possible object is
	   *     {@link String }
	   * 
	   */
	public String getVaultDeviceName() {
		return vaultDeviceName;
	}

	/**
	 * Sets the value of the vaultDeviceName property.
	 * 
	 * @param value
	 *     allowed object is
	 *     {@link String }
	 *     
	 */
	public void setVaultDeviceName(String value) {
		this.vaultDeviceName = value;
	}

	/**
	 * @return the channel number which was active during vault creation.
	 */
	public int getVaultChannelNumber() {
		return vaultChannelNumber;
	}

	/**
	   * Sets the value of the vaultChannelNumber property.
	   * 
	   */
	public void setVaultChannelNumber(int value) {
		this.vaultChannelNumber = value;
	}

	/**
	 * Gets the value of the vaultObjectKey property.
	* 
	* @return
	*     possible object is
	*     {@link String }
	*     
	*/
	public String getVaultObjectKey() {
		return vaultObjectKey;
	}

	/**
	 * Sets the value of the vaultObjectKey property.
	 * 
	 * @param value
	 *     allowed object is
	 *     {@link String }
	 *     
	 */
	public void setVaultObjectKey(String value) {
		this.vaultObjectKey = value;
	}

	/**
	 * Gets the value of the vaultSamplingTimespanMs property.
	 * 
	 */
	public long getVaultSamplingTimespan_ms() {
		return vaultSamplingTimespanMs;
	}

	/**
	 * Sets the value of the vaultSamplingTimespanMs property.
	 * 
	 */
	public void setVaultSamplingTimespan_Ms(long value) {
		this.vaultSamplingTimespanMs = value;
	}

	/**
	 * Gets the value of the logFilePath property.
	 * 
	 * @return
	 *     possible object is
	 *     {@link String }
	 *     
	 */
	public String getLogFilePath() {
		return logFilePath;
	}

	/**
	 * Sets the value of the logFilePath property.
	 * 
	 * @param value
	 *     allowed object is
	 *     {@link String }
	 *     
	 */
	public void setLogFilePath(String value) {
		this.logFilePath = value;
	}

	/**
	 * Gets the value of the logFileLastModified property.
	 * 
	 */
	public long getLogFileLastModified() {
		return logFileLastModified;
	}

	/**
	 * Sets the value of the logFileLastModified property.
	 * 
	 */
	public void setLogFileLastModified(long value) {
		this.logFileLastModified = value;
	}

	/**
	 * Gets the value of the logFileLength property.
	 * 
	 */
	public long getLogFileLength() {
		return logFileLength;
	}

	/**
	 * Sets the value of the logFileLength property.
	 * 
	 */
	public void setLogFileLength(long value) {
		this.logFileLength = value;
	}

	/**
	 * Gets the value of the logObjectDirectory property.
	 * 
	 * @return
	 *     possible object is
	 *     {@link String }
	 *     
	 */
	public String getLogObjectDirectory() {
		return logObjectDirectory;
	}

	/**
	   * Sets the value of the logObjectDirectory property.
	   * 
	   * @param value
	   *     allowed object is
	   *     {@link String }
	   *     
	   */
	public void setLogObjectDirectory(String value) {
		this.logObjectDirectory = value;
	}

	/**
	* Gets the value of the logFileVersion property.
	* 
	*/
	public int getLogFileVersion() {
		return logFileVersion;
	}

	/**
	 * Sets the value of the logFileVersion property.
	 * 
	 */
	public void setLogFileVersion(int value) {
		this.logFileVersion = value;
	}

	/**
	 * Gets the value of the logRecordSetSize property.
	 * 
	 */
	public int getLogRecordSetSize() {
		return logRecordSetSize;
	}

	/**
	   * Sets the value of the logRecordSetSize property.
	   * 
	   */
	public void setLogRecordSetSize(int value) {
		this.logRecordSetSize = value;
	}

	/**
	 * Gets the value of the logRecordSetOrdinal property.
	* 
	*/
	public int getLogRecordSetOrdinal() {
		return logRecordSetOrdinal;
	}

	/**
	   * Sets the value of the logRecordSetOrdinal property.
	   * 
	   */
	public void setLogRecordSetOrdinal(int value) {
		this.logRecordSetOrdinal = value;
	}

	/**
	 * Gets the value of the logRecordsetBaseName property.
	* 
	* @return
	*     possible object is
	*     {@link String }
	*     
	*/
	public String getLogRecordsetBaseName() {
		return logRecordsetBaseName;
	}

	/**
	 * Sets the value of the logRecordsetBaseName property.
	 * 
	 * @param value
	 *     allowed object is
	 *     {@link String }
	 *     
	 */
	public void setLogRecordsetBaseName(String value) {
		this.logRecordsetBaseName = value;
	}

	/**
	 * Gets the value of the logDeviceName property.
	 * 
	 * @return
	 *     possible object is
	 *     {@link String }
	 *     
	 */
	public String getLogDeviceName() {
		return logDeviceName;
	}

	/**
	   * Sets the value of the logDeviceName property.
	   * 
	   * @param value
	   *     allowed object is
	   *     {@link String }
	   *     
	   */
	public void setLogDeviceName(String value) {
		this.logDeviceName = value;
	}

	/**
	* Gets the value of the logChannelNumber property.
	* 
	*/
	public int getLogChannelNumber() {
		return logChannelNumber;
	}

	/**
	 * Sets the value of the logChannelNumber property.
	 * 
	 */
	public void setLogChannelNumber(int value) {
		this.logChannelNumber = value;
	}

	/**
	 * Gets the value of the logObjectKey property.
	 * 
	 * @return
	 *     possible object is
	 *     {@link String }
	 *     
	 */
	public String getLogObjectKey() {
		return logObjectKey;
	}

	/**
	 * Sets the value of the logObjectKey property.
	 * 
	 * @param value
	 *     allowed object is
	 *     {@link String }
	 *     
	 */
	public void setLogObjectKey(String value) {
		this.logObjectKey = value;
	}

	/**
	 * Gets the value of the logStartTimestampMs property.
	 * 
	 */
	public long getLogStartTimestamp_ms() {
		return logStartTimestampMs;
	}

	/**
	 * Sets the value of the logStartTimestampMs property.
	 * 
	 */
	public void setLogStartTimestampMs(long value) {
		this.logStartTimestampMs = value;
	}

	/**
	 * Gets the value of the measurements property.
	 * 
	 * @return
	 *     possible object is
	 *     {@link CompartmentsType }
	 *     
	 */
	public HashMap<Integer, CompartmentType> getMeasurements() {
		if (this.measurements == null) this.measurements = new HashMap<Integer, CompartmentType>();
		return measurements;
	}

	/**
	 * Sets the value of the measurements property.
	 * 
	 * @param value
	 *     allowed object is
	 *     {@link CompartmentsType }
	 *     
	 */
	public void setMeasurements(HashMap<Integer, CompartmentType> value) {
		this.measurements = value;
	}

	/**
	 * Gets the value of the settlements property.
	 * 
	 * @return
	 *     possible object is
	 *     {@link CompartmentsType }
	 *     
	 */
	public HashMap<Integer, CompartmentType> getSettlements() {
		if (this.settlements == null) this.settlements = new HashMap<Integer, CompartmentType>();
		return settlements;
	}

	/**
	 * Sets the value of the settlements property.
	 * 
	 * @param value
	 *     allowed object is
	 *     {@link CompartmentsType }
	 *     
	 */
	public void setSettlements(HashMap<Integer, CompartmentType> value) {
		this.settlements = value;
	}

	/**
	 * Gets the value of the scores property.
	 * 
	 * @return
	 *     possible object is
	 *     {@link PointsType }
	 *     
	 */
	public HashMap<Integer, PointType> getScores() {
		if (this.scores == null) this.scores = new HashMap<Integer, PointType>();
		return scores;
	}

	/**
	 * Sets the value of the scores property.
	 * 
	 * @param value
	 *     allowed object is
	 *     {@link PointsType }
	 *     
	 */

	public void setScores(HashMap<Integer, PointType> value) {
		this.scores = value;
	}

	@Deprecated // for marshalling purposes only
	public HistoVault() {
	}

	/**
	 * @param objectDirectory validated object key
	 * @param filePath file name + lastModified + file length are a simple solution for getting a SHA-1 hash from the file contents
	 * @param fileLastModified_ms
	 * @param fileLength in bytes
	 * @param fileVersion is the version of the log origin file
	 * @param logRecordSetSize is the number of recordsets in the log origin file
	 * @param logRecordSetOrdinal identifies multiple recordsets in one single file (0-based)
	 * @param logRecordsetBaseName the base name without recordset number
	 * @param logStartTimestamp_ms of the log or recordset
	 * @param logDeviceName 
	 * @param logChannelNumber may differ from UI settings in case of channel mix
	 * @param logObjectKey may differ from UI settings (empty in OSD files, validated parent path for bin files)
	 */
	private HistoVault(String objectDirectory, Path filePath, long fileLastModified_ms, long fileLength, int fileVersion, int logRecordSetSize, int logRecordSetOrdinal, String logRecordSetBaseName,
			String logDeviceName, long logStartTimestamp_ms, int logChannelNumber, String logObjectKey) {
		this.vaultDataExplorerVersion = GDE.VERSION;
		this.vaultDeviceKey = HistoVault.getActiveDeviceKey();
		this.vaultDeviceName = this.application.getActiveDevice().getName();
		this.vaultChannelNumber = this.application.getActiveChannelNumber();
		this.vaultObjectKey = this.application.getObjectKey();
		this.vaultSamplingTimespanMs = this.settings.getSamplingTimespan_ms();
		this.logFilePath = filePath.toString(); // toString in order to avoid 'Object' during marshalling
		this.logFileLastModified = fileLastModified_ms;
		this.logFileLength = fileLength;
		this.logFileVersion = fileVersion;
		this.logRecordSetSize = logRecordSetSize;
		this.logObjectDirectory = objectDirectory;
		this.logRecordSetOrdinal = logRecordSetOrdinal;
		this.logRecordsetBaseName = logRecordSetBaseName;
		this.logDeviceName = logDeviceName;
		this.logChannelNumber = logChannelNumber;
		this.logObjectKey = logObjectKey;
		this.logStartTimestampMs = logStartTimestamp_ms;

		this.vaultDirectory = HistoVault.getVaultsDirectory();
		this.vaultName = HistoVault.getVaultName(filePath, fileLastModified_ms, fileLength, logRecordSetOrdinal);
		this.vaultCreatedMs = System.currentTimeMillis();
		if (log.isLoggable(Level.FINER)) log.log(Level.FINER,
				String.format("HistoVault.ctor  objectDirectory=%s  path=%s  lastModified=%s  logRecordSetOrdinal=%d  logRecordSetBaseName=%s  startTimestamp_ms=%d   channelConfigNumber=%d   objectKey=%s", //$NON-NLS-1$
						objectDirectory, filePath.getFileName().toString(), logRecordSetBaseName, StringHelper.getFormatedTime("yyyy-MM-dd HH:mm:ss.SSS", this.logFileLastModified), //$NON-NLS-1$
						StringHelper.getFormatedTime("yyyy-MM-dd HH:mm:ss.SSS", this.logStartTimestampMs), logChannelNumber, logObjectKey)); //$NON-NLS-1$
		if (log.isLoggable(Level.FINER)) log.log(Level.FINER, String.format("vaultDirectory=%s  vaultName=%s", this.vaultDirectory, this.vaultName)); //$NON-NLS-1$
	}

	/**
	 * @param objectDirectory validated object key
	 * @param file is the log origin file (not a link file)
	 * @param fileVersion is the version of the log origin file
	 * @param logRecordSetSize is the number of recordsets in the log origin file
	 * @param logRecordSetOrdinal identifies multiple recordsets in one single file (0-based)
	 * @param logRecordsetBaseName the base name without recordset number
	 * @param logStartTimestamp_ms of the log or recordset
	 * @param logDeviceName 
	 * @param logChannelNumber may differ from UI settings in case of channel mix
	 * @param logObjectKey may differ from UI settings (empty in OSD files, validated parent path for bin files)
	 * @return new instance with a basic set of data
	 */
	public static HistoVault createTruss(String objectDirectory, File file, int fileVersion, int logRecordSetSize, int logRecordSetOrdinal, String logRecordsetBaseName, String logDeviceName,
			long logStartTimestamp_ms, int logChannelNumber, String logObjectKey) {
		HistoVault newHistoVault = new HistoVault(objectDirectory, file.toPath(), file.lastModified(), file.length(), fileVersion, logRecordSetSize, logRecordSetOrdinal, logRecordsetBaseName,
				logDeviceName, logStartTimestamp_ms, logChannelNumber, logObjectKey);
		return newHistoVault;
	}

	/**
	 * @param objectDirectory validated object key
	 * @param file is the bin origin file (not a link file)
	 * @param fileVersion is the version of the log origin file
	 * @param logRecordSetSize is the number of recordsets in the log origin file
	 * @param logRecordsetBaseName the base name without recordset number
	 * @return new instance with a basic set of data
	 */
	public static HistoVault createTruss(String objectDirectory, File file, int fileVersion, int logRecordSetSize, String logRecordsetBaseName) {
		return createTruss(objectDirectory, file, fileVersion, logRecordSetSize, 0, logRecordsetBaseName, "native", file.lastModified(), DataExplorer.getInstance().getActiveChannelNumber(), //$NON-NLS-1$
				objectDirectory);
	}

	/**
	 * @param fullQualifiedFileName path
	 * @return new instance 
	 */
	public static HistoVault load(Path fullQualifiedFileName) {
		HistoVault newHistoVault = null;
		try {
			newHistoVault = (HistoVault) HistoVault.getUnmarshaller().unmarshal(fullQualifiedFileName.toFile());
		}
		catch (JAXBException e) {
			e.printStackTrace();
		}
		return newHistoVault;
	}

	/**
	 * @param inputStream
	 * @return new instance 
	 */
	public static HistoVault load(InputStream inputStream) {
		HistoVault newHistoVault = null;
		try {
			newHistoVault = (HistoVault) HistoVault.getUnmarshaller().unmarshal(inputStream);
		}
		catch (JAXBException e) {
			e.printStackTrace();
		}
		return newHistoVault;
	}

	/**
	 * writes device properties XML to given full qualified file name
	 * @param fullQualifiedFileName
	 */
	public void store(Path fullQualifiedFileName) {
		try {
			HistoVault.getMarshaller().marshal(this, fullQualifiedFileName.toFile());
		}
		catch (JAXBException e) {
			e.printStackTrace();
		}
	}

	/**
	 * writes device properties XML to given full qualified file name
	 * @param outputStream
	 */
	public void store(OutputStream outputStream) {
		try {
			HistoVault.getMarshaller().marshal(this, outputStream);
		}
		catch (JAXBException e) {
			e.printStackTrace();
		}
	}

	/**
	 * @return context singleton (creating the context is slow)
	 */
	private static JAXBContext getJaxbContext() {
		if (HistoVault.jaxbContext == null) {
			try {
				HistoVault.jaxbContext = JAXBContext.newInstance(HistoVault.class);
			}
			catch (Exception e) {
				throw new RuntimeException(e);
			}
		}
		return HistoVault.jaxbContext;
	}

	/**
	 * @return cached instance (unmarshaller is not thread safe) which is ~100 ms faster than creating a new instance from a cached JaxbContext instance
	 */
	private static Unmarshaller getUnmarshaller() {
		if (HistoVault.jaxbUnmarshaller == null) {
			final Path path = getCacheDirectory().resolve(Settings.HISTO_CACHE_ENTRIES_XSD_NAME);
			try {
				HistoVault.jaxbUnmarshaller = getJaxbContext().createUnmarshaller();
				HistoVault.jaxbUnmarshaller.setSchema(SchemaFactory.newInstance(XMLConstants.W3C_XML_SCHEMA_NS_URI).newSchema(path.toFile()));
			}
			catch (Exception e) {
				throw new RuntimeException(e);
			}
		}
		return HistoVault.jaxbUnmarshaller;
	}

	/**
	 * @return cached instance (marshaller is not thread safe) which is ~100 ms faster than creating a new instance from a cached JaxbContext instance
	 */
	private static Marshaller getMarshaller() {
		if (HistoVault.jaxbMarshaller == null) {
			final Path path = getCacheDirectory().resolve(Settings.HISTO_CACHE_ENTRIES_XSD_NAME);
			try {
				HistoVault.jaxbMarshaller = getJaxbContext().createMarshaller();
				HistoVault.jaxbMarshaller.setProperty(Marshaller.JAXB_FORMATTED_OUTPUT, true);
				HistoVault.jaxbMarshaller.setSchema(SchemaFactory.newInstance(XMLConstants.W3C_XML_SCHEMA_NS_URI).newSchema(path.toFile()));
			}
			catch (Exception e) {
				throw new RuntimeException(e);
			}
		}
		return HistoVault.jaxbMarshaller;
	}

	/**
	 * checks if the vault conforms to the current environment.
	 * does not check if the file is accessible, carries the last modified timestamp and holds the recordset ordinal.
	 * @return true if the vault object conforms to current versions of the Data Explorer / device XML, to current user settings (e.g. sampling timespan) and to various additional attributes
	 */
	public boolean isValid() {
		return this.vaultName.equals(HistoVault.getVaultName(Paths.get(this.logFilePath), this.logFileLastModified, this.logFileLength, this.logRecordSetOrdinal));
	}

	/**
	 * checks if the vault conforms to the current environment, if the file is accessible and has the same last modified timestamp.
	 * reads the history recordset from the file based on the active device, converts it into a vault and compares the key values.
	 * @return true if the vault's origin file exists and produces the same vault key values compared to this vault
	 * @throws DataInconsitsentException 
	 * @throws NotSupportedFileFormatException 
	 * @throws IOException 
	 */
	public boolean isSubstantiated() throws IOException, NotSupportedFileFormatException, DataInconsitsentException {
		File file = getCacheDirectory().resolve(this.vaultDirectory).resolve(this.vaultName).toFile();
		if (this.vaultName.equals(HistoVault.getVaultName(Paths.get(this.logFilePath), file.lastModified(), file.length(), this.logRecordSetOrdinal))) {
			List<HistoVault> trusses = new ArrayList<HistoVault>();
			trusses.add(this);
			List<HistoVault> histoVaults = HistoOsdReaderWriter.readHisto(file.toPath(), trusses);
			return this.getVaultName().equals(histoVaults.get(0).getVaultName());
		}
		else {
			return false;
		}
	}

	/**
	 * @param newVaultsDirectory directory or zip file name
	 * @return true if the vault directory name conforms to current versions of the Data Explorer / device XML, to the current channel and to user settings (e.g. sampling timespan) and to various additional attributes
	 */
	public static boolean isValidDirectory(String newVaultsDirectory) {
		return newVaultsDirectory.equals(HistoVault.getVaultsDirectory());
	}

	/**
	 * the vaults directory is determined without any log file contents.
	 * this supports vault directory scanning functions in the future.
	 * @return directory or zip file name as a unique identifier encoding the data explorer version, the device xml file contents(sha1) plus channel number and some settings values
	 */
	public static String getVaultsDirectory() {
		String tmpSubDirectoryLongKey = String.format("%s,%s,%d,%d,%f,%f", GDE.VERSION, HistoVault.getActiveDeviceKey(), DataExplorer.getInstance().getActiveChannelNumber(), //$NON-NLS-1$
				Settings.getInstance().getSamplingTimespan_ms(), Settings.getInstance().getMinmaxQuantileDistance(), Settings.getInstance().getAbsoluteTransitionLevel());
		return HistoVault.sha1(tmpSubDirectoryLongKey);

	}

	/**
	 * @return the path to the directory or zip file
	 */
	public static Path getVaultsFolder() {
		return getCacheDirectory().resolve(getVaultsDirectory());
	}

	public static Path getCacheDirectory() {
		return Paths.get(Settings.getInstance().getApplHomePath(), Settings.HISTO_CACHE_ENTRIES_DIR_NAME);
	}

	/**
	 * the vaults file name is determined without any log file contents and without file location properties (path).
	 * this supports creating a truss or accessing a vault without having read the original log file.
	 * @param newLogFileName file name + lastModified + newFileLength are a simple solution for getting a SHA-1 hash from the file contents
	 * @param newFileLastModified_ms 
	 * @param newFileLength in bytes
	 * @param newLogRecordSetOrdinal identifies multiple recordsets in one single file (0-based)
	 * @return the file name as a unique identifier (sha1)
	 */
	private static String getVaultName(Path newLogFileName, long newFileLastModified_ms, long newFileLength, int newLogRecordSetOrdinal) {
		return sha1(HistoVault.getVaultsDirectory() + String.format("%s,%d,%d,%d", newLogFileName.getFileName(), newFileLastModified_ms, newFileLength, newLogRecordSetOrdinal)); //$NON-NLS-1$
	}

	/**
	 * @param newLogFileName file name + lastModified + newFileLength are a simple solution for getting a SHA-1 hash from the file contents
	 * @param newFileLastModified_ms 
	 * @param newFileLength in bytes
	 * @param newLogRecordSetOrdinal identifies multiple recordsets in one single file (0-based)
	 * @return the path with filename as a unique identifier (sha1)
	 */
	public static Path getVaultRelativePath(Path newLogFileName, long newFileLastModified_ms, long newFileLength, int newLogRecordSetOrdinal) {
		// do not include as these attributes are determined after reading the histoset: logChannelNumber, logObjectKey, logStartTimestampMs
		Path subDirectory = Paths.get(HistoVault.getVaultsDirectory());
		return subDirectory.resolve(HistoVault.getVaultName(newLogFileName.getFileName(), newFileLastModified_ms, newFileLength, newLogRecordSetOrdinal));
	}

	/**
	 * @return sha1 key as a unique identifier for the device xml file contents
	 */
	private static String getActiveDeviceKey() {
		File file = new File(DataExplorer.getInstance().getActiveDevice().getPropertiesFileName());
		if (HistoVault.activeDeviceKey == null || HistoVault.activeDevicePath == null || !HistoVault.activeDevicePath.equals(file.toPath())
				|| HistoVault.activeDeviceLastModified_ms != file.lastModified()) {
			try {
				HistoVault.activeDeviceKey = HistoVault.sha1(file);
				HistoVault.activeDevicePath = file.toPath();
				HistoVault.activeDeviceLastModified_ms = file.lastModified();
			}
			catch (IOException e) {
				e.printStackTrace();
			}
		}
		return HistoVault.activeDeviceKey;
	}

	/**
	 * source: http://www.sha1-online.com/sha1-java/
	 * @param input
	 * @return the SHA-1 hash value rendered as a hexadecimal number, 40 digits long
	 */
	private static String sha1(String input) {
		byte[] hashBytes = null;
		try {
			hashBytes = MessageDigest.getInstance("SHA1").digest(input.getBytes()); //$NON-NLS-1$
		}
		catch (NoSuchAlgorithmException e) {
			e.printStackTrace();
		}
		StringBuilder sb = new StringBuilder();
		for (int i = 0; i < hashBytes.length; i++) {
			sb.append(Integer.toString((hashBytes[i] & 0xff) + 0x100, 16).substring(1));
		}
		return sb.toString();
	}

	/**
	 * source: http://www.sha1-online.com/sha1-java/
	 * @param file 
	 * @return the file's full data SHA1 checksum
	 * @throws IOException
	 */
	private static String sha1(File file) throws IOException {
		MessageDigest sha1Digest = null;
		try {
			sha1Digest = MessageDigest.getInstance("SHA1"); //$NON-NLS-1$
		}
		catch (NoSuchAlgorithmException e) {
			e.printStackTrace();
		}
		byte[] hashBytes = null;
		try (FileInputStream fis = new FileInputStream(file)) {
			byte[] data = new byte[8192]; // most file systems are configured to use block sizes of 4096 or 8192
			int read = 0;
			while ((read = fis.read(data)) != -1) {
				sha1Digest.update(data, 0, read);
			}
			hashBytes = sha1Digest.digest();
		}
		StringBuilder sb = new StringBuilder();
		for (int i = 0; i < hashBytes.length; i++) {
			sb.append(Integer.toString((hashBytes[i] & 0xff) + 0x100, 16).substring(1));
		}
		return sb.toString();
	}

	public void promoteTruss(RecordSet recordSet, Integer[] scorePoints) {
		if (recordSet.getRecordDataSize(true) > 0) {
			this.logStartTimestampMs = recordSet.getStartTimeStamp();
			{
				List<MeasurementType> channelMeasurements = this.device.getChannelMeasuremts(this.getLogChannelNumber());
				for (int i = 0; i < recordSet.getRecordNames().length; i++) {
					MeasurementType measurementType = channelMeasurements.get(i);
					Record record = recordSet.get(recordSet.getRecordNames()[i]);
					CompartmentType entryPoints = new CompartmentType(i, measurementType.getName(), DataTypes.fromDataType(record.getDataType()));
					this.getMeasurements().put(i, entryPoints);
					entryPoints.setTrails(new HashMap<Integer, PointType>());

					if (record == null) {
						if (log.isLoggable(Level.WARNING)) log.log(Level.WARNING, String.format("no record found for measurementType.getName()=%s %s", measurementType.getName(), this.getLogFilePath())); //$NON-NLS-1$
					}
					else if (!record.hasReasonableData()) {
						if (log.isLoggable(Level.FINE)) log.log(Level.FINE, String.format("no reasonable data for measurementType.getName()=%s %s", measurementType.getName(), this.getLogFilePath())); //$NON-NLS-1$
					}
					else {
						StatisticsType measurementStatistics = measurementType.getStatistics();
						int triggerRefOrdinal = -1;
						if (measurementStatistics != null) { // todo this creates trail types mismatch  :  && record.hasReasonableData()) {
							if (measurementStatistics.getTriggerRefOrdinal() != null) {
								int tmpOrdinal = measurementStatistics.getTriggerRefOrdinal().intValue();
								//todo	if (record.isDisplayable()) { the record may be displayable later --- but note that calculating trigger ranges requires displayable true 
								triggerRefOrdinal = tmpOrdinal;
								//								}
							}
							boolean isTriggerLevel = measurementStatistics.getTrigger() != null;
							if (measurementStatistics.isAvg()) {
								if (isTriggerLevel)
									entryPoints.addPoint(TrailTypes.REAL_AVG, record.getAvgValueTriggered() != Integer.MIN_VALUE ? record.getAvgValueTriggered() : 0);
								else if (triggerRefOrdinal < 0 || record.getAvgValueTriggered(triggerRefOrdinal) != Integer.MIN_VALUE) //
									entryPoints.addPoint(TrailTypes.REAL_AVG, triggerRefOrdinal < 0 ? record.getAvgValue() : (Integer) record.getAvgValueTriggered(triggerRefOrdinal));
							}
							else {
								entryPoints.addPoint(TrailTypes.REAL_AVG, record.getAvgValue());
							}
							if (measurementStatistics.isMax()) {
								if (isTriggerLevel)
									entryPoints.addPoint(TrailTypes.REAL_MAX, record.getMaxValueTriggered());
								else if (triggerRefOrdinal < 0 || record.getMaxValueTriggered(triggerRefOrdinal) != Integer.MIN_VALUE) //
									entryPoints.addPoint(TrailTypes.REAL_MAX, triggerRefOrdinal < 0 ? record.getRealMaxValue() : (Integer) record.getMaxValueTriggered(triggerRefOrdinal));
							}
							else {
								entryPoints.addPoint(TrailTypes.REAL_MAX, record.getRealMaxValue());
							}
							if (measurementStatistics.isMin()) {
								if (isTriggerLevel)
									entryPoints.addPoint(TrailTypes.REAL_MIN, record.getMinValueTriggered());
								else if (triggerRefOrdinal < 0 || record.getMinValueTriggered(triggerRefOrdinal) != Integer.MAX_VALUE) //
									entryPoints.addPoint(TrailTypes.REAL_MIN, triggerRefOrdinal < 0 ? record.getRealMinValue() : (Integer) record.getMinValueTriggered(triggerRefOrdinal));
							}
							else {
								entryPoints.addPoint(TrailTypes.REAL_MIN, record.getRealMinValue());
							}
							if (measurementStatistics.isSigma()) {
								if (isTriggerLevel)
									entryPoints.addPoint(TrailTypes.REAL_SD, record.getSigmaValueTriggered());
								else if (triggerRefOrdinal < 0 || record.getSigmaValueTriggered(triggerRefOrdinal) != Integer.MIN_VALUE) //
									entryPoints.addPoint(TrailTypes.REAL_SD, triggerRefOrdinal < 0 ? (Integer) record.getSigmaValue() : (Integer) record.getSigmaValueTriggered(triggerRefOrdinal));
							}
							else {
								entryPoints.addPoint(TrailTypes.REAL_SD, record.getSigmaValue());
							}
							if (measurementStatistics.getSumByTriggerRefOrdinal() != null) {
								if (measurementStatistics.getSumTriggerText() != null && measurementStatistics.getSumTriggerText().length() > 1)
									entryPoints.addPoint(TrailTypes.REAL_SUM_TRIGGERED, record.getSumTriggeredRange());
								else if (measurementStatistics.getSumByTriggerRefOrdinal() != null) {
									entryPoints.addPoint(TrailTypes.REAL_SUM_TRIGGERED, record.getSumTriggeredRange(measurementStatistics.getSumByTriggerRefOrdinal()));
								}
								if (measurementStatistics.getRatioText() != null && measurementStatistics.getRatioText().length() > 1 && measurementStatistics.getRatioRefOrdinal() != null) {
									Record referencedRecord = recordSet.get(measurementStatistics.getRatioRefOrdinal().intValue());
									StatisticsType referencedStatistics = this.device.getMeasurementStatistic(this.getLogChannelNumber(), measurementStatistics.getRatioRefOrdinal());
									if (referencedRecord != null && (referencedStatistics.isAvg() || referencedStatistics.isMax()))
										// todo trigger ratio is multiplied by 1000 (per mille)
										if (referencedStatistics.isAvg())
										entryPoints.addPoint(TrailTypes.REAL_AVG_RATIO_TRIGGERED, (int) Math.round(referencedRecord.getAvgValue() * 1000.0 / record.getSumTriggeredRange(measurementStatistics.getSumByTriggerRefOrdinal())));
										else if (referencedStatistics.isMax()) //
											entryPoints.addPoint(TrailTypes.REAL_MAX_RATIO_TRIGGERED,
													(int) Math.round(referencedRecord.getMaxValue() * 1000.0 / record.getSumTriggeredRange(measurementStatistics.getSumByTriggerRefOrdinal())));
								}
							}
							if (measurementStatistics.getTrigger() != null && measurementStatistics.getSumTriggerTimeText() != null && measurementStatistics.getSumTriggerTimeText().length() > 1) {
								entryPoints.addPoint(TrailTypes.REAL_TIME_SUM_TRIGGERED, record.getTimeSumTriggeredRange_ms());
							}
							if (measurementStatistics.isCountByTrigger() != null) {
								entryPoints.addPoint(TrailTypes.REAL_COUNT_TRIGGERED, record.getTriggerRanges() != null ? record.getTriggerRanges().size() : 0);
							}
						}
						if (record.realSize() != 0) {
							entryPoints.addPoint(TrailTypes.REAL_FIRST, record.realRealGet(0));
							entryPoints.addPoint(TrailTypes.REAL_LAST, record.realRealGet(record.size() - 1));

							boolean isSampled = scorePoints[ScoreLabelTypes.TOTAL_READINGS.ordinal()] != null && scorePoints[ScoreLabelTypes.TOTAL_READINGS.ordinal()] > recordSet.getRecordDataSize(true);
							final ChannelPropertyType channelProperty = this.device.getDeviceConfiguration().getChannelProperty(ChannelPropertyTypes.OUTLIER_SIGMA);
							final double outlierSigma = channelProperty.getValue() != null && !channelProperty.getValue().isEmpty() ? Double.parseDouble(channelProperty.getValue())
									: HistoSettlement.outlierSigmaDefault;
							final ChannelPropertyType channelProperty2 = this.device.getDeviceConfiguration().getChannelProperty(ChannelPropertyTypes.OUTLIER_RANGE_FACTOR);
							final double outlierRangeFaktor = channelProperty2.getValue() != null && !channelProperty2.getValue().isEmpty() ? Double.parseDouble(channelProperty2.getValue())
									: HistoSettlement.outlierRangeFactorDefault;
							// invoke translation because of GPS coordinates (decimal fraction range is x.0000 to x.5999 [recurring decimal])
							Quantile quantile = new Quantile(record.getTranslatedValues(), isSampled ? EnumSet.of(Fixings.IS_SAMPLE) : EnumSet.noneOf(Fixings.class), outlierSigma, outlierRangeFaktor);
							entryPoints.addPoint(TrailTypes.AVG, (int) (this.device.reverseTranslateValue(record, quantile.getAvgFigure()) * 1000.));
							entryPoints.addPoint(TrailTypes.MAX, (int) (this.device.reverseTranslateValue(record, quantile.getMaxFigure()) * 1000.));
							entryPoints.addPoint(TrailTypes.MIN, (int) (this.device.reverseTranslateValue(record, quantile.getMinFigure()) * 1000.));
							entryPoints.addPoint(TrailTypes.SD, (int) (this.device.reverseTranslateValue(record, quantile.getSigmaFigure()) * 1000.));
							entryPoints.addPoint(TrailTypes.Q0, (int) (this.device.reverseTranslateValue(record, quantile.getQuartile0()) * 1000.));
							entryPoints.addPoint(TrailTypes.Q1, (int) (this.device.reverseTranslateValue(record, quantile.getQuartile1()) * 1000.));
							entryPoints.addPoint(TrailTypes.Q2, (int) (this.device.reverseTranslateValue(record, quantile.getQuartile2()) * 1000.));
							entryPoints.addPoint(TrailTypes.Q3, (int) (this.device.reverseTranslateValue(record, quantile.getQuartile3()) * 1000.));
							entryPoints.addPoint(TrailTypes.Q4, (int) (this.device.reverseTranslateValue(record, quantile.getQuartile4()) * 1000.));
							entryPoints.addPoint(TrailTypes.Q_25_PERMILLE, (int) (this.device.reverseTranslateValue(record, quantile.getQuantile(.025)) * 1000.));
							entryPoints.addPoint(TrailTypes.Q_975_PERMILLE, (int) (this.device.reverseTranslateValue(record, quantile.getQuantile(.975)) * 1000.));
							entryPoints.addPoint(TrailTypes.Q_LOWER_WHISKER, (int) (this.device.reverseTranslateValue(record, quantile.getQuantileLowerWhisker()) * 1000.));
							entryPoints.addPoint(TrailTypes.Q_UPPER_WHISKER, (int) (this.device.reverseTranslateValue(record, quantile.getQuantileUpperWhisker()) * 1000.));
							entryPoints.addPoint(TrailTypes.FIRST, (int) (this.device.reverseTranslateValue(record, quantile.getFirstFigure()) * 1000.));
							entryPoints.addPoint(TrailTypes.LAST, (int) (this.device.reverseTranslateValue(record, quantile.getLastFigure()) * 1000.));
							// trigger trail types sum are not supported for measurements
							entryPoints.addPoint(TrailTypes.SUM, (int) (0 * 1000.));
							entryPoints.addPoint(TrailTypes.COUNT, (int) (quantile.getSizeFigure() * 1000.));
						}
						log.log(Level.FINER, record.getName() + " data ", entryPoints); //$NON-NLS-1$
					}
				}
				{
					// step: build transitions
					HistoTransitions transitions = new HistoTransitions(recordSet);
					transitions.add4Channel(this.logChannelNumber);

					// step: calculate the histo settlements
					LinkedHashMap<String, HistoSettlement> histoSettlements = new LinkedHashMap<String, HistoSettlement>();
					if (transitions.getTransitionCount() > 0) { // todo implement evaluations w/o transitions
						for (SettlementType settlementType : this.device.getDeviceConfiguration().getChannel(this.logChannelNumber).getSettlements().values()) {
							if (settlementType.getEvaluation() != null) { // todo decide if evaluations without transition are useful
								final TransitionFigureType transitionFigureType = settlementType.getEvaluation().getTransitionFigure();
								final TransitionAmountType transitionAmountType = settlementType.getEvaluation().getTransitionAmount();
								final TransitionCalculusType calculationType = settlementType.getEvaluation().getTransitionCalculus();
								if (transitionFigureType != null) {
									HistoSettlement histoSettlement = new HistoSettlement(settlementType, recordSet, this.logChannelNumber);
									histoSettlement.addFromTransitions(transitions.getTransitions(transitionFigureType.getTransitionGroupId()).values());
									histoSettlements.put(settlementType.getName(), histoSettlement);
								}
								else if (transitionAmountType != null) {
									HistoSettlement histoSettlement = new HistoSettlement(settlementType, recordSet, this.logChannelNumber);
									histoSettlement.addFromTransitions(transitions.getTransitions(transitionAmountType.getTransitionGroupId()).values());
									histoSettlements.put(settlementType.getName(), histoSettlement);
								}
								else if (calculationType != null) {
									HistoSettlement histoSettlement = new HistoSettlement(settlementType, recordSet, this.logChannelNumber);
									histoSettlement.addFromTransitions(transitions.getTransitions(calculationType.getTransitionGroupId()).values());
									histoSettlements.put(settlementType.getName(), histoSettlement);
								}
								else {
									throw new UnsupportedOperationException();
								}
							}
						}
					}

					// step: consume settlements
					for (Entry<String, HistoSettlement> entry : histoSettlements.entrySet()) {
						HistoSettlement histoSettlement = entry.getValue();
						SettlementType settlementType = histoSettlement.getSettlement();
						CompartmentType entryPoints = new CompartmentType(settlementType.getSettlementId(), settlementType.getName(), DataTypes.DEFAULT);
						this.getSettlements().put(settlementType.getSettlementId(), entryPoints);
						entryPoints.setTrails(new HashMap<Integer, PointType>());

						if (histoSettlement.realSize() != 0 && histoSettlement.hasReasonableData()) {
							boolean isSampled = scorePoints[ScoreLabelTypes.TOTAL_READINGS.ordinal()] != null && scorePoints[ScoreLabelTypes.TOTAL_READINGS.ordinal()] > recordSet.getRecordDataSize(true);

							final ChannelPropertyType channelProperty = this.device.getDeviceConfiguration().getChannelProperty(ChannelPropertyTypes.OUTLIER_SIGMA);
							final double outlierSigma = channelProperty.getValue() != null && !channelProperty.getValue().isEmpty() ? Double.parseDouble(channelProperty.getValue())
									: HistoSettlement.outlierSigmaDefault;
							final ChannelPropertyType channelProperty2 = this.device.getDeviceConfiguration().getChannelProperty(ChannelPropertyTypes.OUTLIER_RANGE_FACTOR);
							final double outlierRangeFaktor = channelProperty2.getValue() != null && !channelProperty2.getValue().isEmpty() ? Double.parseDouble(channelProperty2.getValue())
									: HistoSettlement.outlierRangeFactorDefault;
							Quantile quantile = new Quantile(histoSettlement.getTranslatedValues(), isSampled ? EnumSet.of(Fixings.IS_SAMPLE) : EnumSet.noneOf(Fixings.class), outlierSigma, outlierRangeFaktor);

							entryPoints.addPoint(TrailTypes.REAL_AVG, (int) (histoSettlement.reverseTranslateValue(quantile.getAvgFigure()) * 1000.));
							entryPoints.addPoint(TrailTypes.REAL_MAX, (int) (histoSettlement.reverseTranslateValue(quantile.getMaxFigure()) * 1000.));
							entryPoints.addPoint(TrailTypes.REAL_MIN, (int) (histoSettlement.reverseTranslateValue(quantile.getMinFigure()) * 1000.));
							entryPoints.addPoint(TrailTypes.REAL_SD, (int) (histoSettlement.reverseTranslateValue(quantile.getSigmaFigure()) * 1000.));
							entryPoints.addPoint(TrailTypes.REAL_FIRST, (int) (histoSettlement.reverseTranslateValue(quantile.getFirstFigure()) * 1000.));
							entryPoints.addPoint(TrailTypes.REAL_LAST, (int) (histoSettlement.reverseTranslateValue(quantile.getLastFigure()) * 1000.));
							entryPoints.addPoint(TrailTypes.REAL_SUM, (int) (histoSettlement.reverseTranslateValue(quantile.getSumFigure()) * 1000.));
							entryPoints.addPoint(TrailTypes.REAL_COUNT, (int) (histoSettlement.reverseTranslateValue(quantile.getSizeFigure() * 1000) * 1000.));

							entryPoints.addPoint(TrailTypes.AVG, (int) (histoSettlement.reverseTranslateValue(quantile.getAvgFigure()) * 1000.));
							entryPoints.addPoint(TrailTypes.MAX, (int) (histoSettlement.reverseTranslateValue(quantile.getMaxFigure()) * 1000.));
							entryPoints.addPoint(TrailTypes.MIN, (int) (histoSettlement.reverseTranslateValue(quantile.getMinFigure()) * 1000.));
							entryPoints.addPoint(TrailTypes.SD, (int) (histoSettlement.reverseTranslateValue(quantile.getSigmaFigure()) * 1000.));
							entryPoints.addPoint(TrailTypes.Q0, (int) (histoSettlement.reverseTranslateValue(quantile.getQuartile0()) * 1000.));
							entryPoints.addPoint(TrailTypes.Q1, (int) (histoSettlement.reverseTranslateValue(quantile.getQuartile1()) * 1000.));
							entryPoints.addPoint(TrailTypes.Q2, (int) (histoSettlement.reverseTranslateValue(quantile.getQuartile2()) * 1000.));
							entryPoints.addPoint(TrailTypes.Q3, (int) (histoSettlement.reverseTranslateValue(quantile.getQuartile3()) * 1000.));
							entryPoints.addPoint(TrailTypes.Q4, (int) (histoSettlement.reverseTranslateValue(quantile.getQuartile4()) * 1000.));
							entryPoints.addPoint(TrailTypes.Q_25_PERMILLE, (int) (histoSettlement.reverseTranslateValue(quantile.getQuantile(.025)) * 1000.));
							entryPoints.addPoint(TrailTypes.Q_975_PERMILLE, (int) (histoSettlement.reverseTranslateValue(quantile.getQuantile(.975)) * 1000.));
							entryPoints.addPoint(TrailTypes.Q_LOWER_WHISKER, (int) (histoSettlement.reverseTranslateValue(quantile.getQuantileLowerWhisker()) * 1000.));
							entryPoints.addPoint(TrailTypes.Q_UPPER_WHISKER, (int) (histoSettlement.reverseTranslateValue(quantile.getQuantileUpperWhisker()) * 1000.));
							entryPoints.addPoint(TrailTypes.FIRST, (int) (histoSettlement.reverseTranslateValue(quantile.getFirstFigure()) * 1000.));
							entryPoints.addPoint(TrailTypes.LAST, (int) (histoSettlement.reverseTranslateValue(quantile.getLastFigure()) * 1000.));
							entryPoints.addPoint(TrailTypes.SUM, (int) (histoSettlement.reverseTranslateValue(quantile.getSumFigure()) * 1000.));
							entryPoints.addPoint(TrailTypes.COUNT, (int) (quantile.getSizeFigure() * 1000.));
						}
						log.log(Level.FINER, histoSettlement.getName() + " data ", this.getSettlements()); //$NON-NLS-1$
					}
					{
						scorePoints[ScoreLabelTypes.DURATION_MM.ordinal()] = (int) (recordSet.getMaxTime_ms() / 60000. * 1000. + .5);
						scorePoints[ScoreLabelTypes.AVERAGE_TIME_STEP_MS.ordinal()] = (int) (recordSet.getAverageTimeStep_ms() * 1000.);
						scorePoints[ScoreLabelTypes.MAXIMUM_TIME_STEP_MS.ordinal()] = (int) (recordSet.getMaximumTimeStep_ms() * 1000.);
						scorePoints[ScoreLabelTypes.MINIMUM_TIME_STEP_MS.ordinal()] = (int) (recordSet.getMinimumTimeStep_ms() * 1000.);
						scorePoints[ScoreLabelTypes.SIGMA_TIME_STEP_MS.ordinal()] = (int) (recordSet.getSigmaTimeStep_ms() * 1000.);
						scorePoints[ScoreLabelTypes.SAMPLED_READINGS.ordinal()] = recordSet.getRecordDataSize(true);

						for (ScoreLabelTypes scoreLabelTypes : EnumSet.allOf(ScoreLabelTypes.class)) {
							if (scorePoints[scoreLabelTypes.ordinal()] != null) {
								this.getScores().put(scoreLabelTypes.ordinal(), new PointType(scoreLabelTypes.ordinal(), scoreLabelTypes.toString(), scorePoints[scoreLabelTypes.ordinal()]));
							}
						}
						log.log(Level.FINE, "scores ", this.getScores()); //$NON-NLS-1$
					}
				}
			}
		}
	}

	/**
	 * @param measurementOrdinal may specify an ordinal which is not present in the vault (earlier osd file - measurements added in the meantime)
	 * @return empty in case of unavailable measurement
	 */
	public HashMap<Integer, PointType> getMeasurementPoints(int measurementOrdinal) {
		return this.getMeasurements().containsKey(measurementOrdinal) ? new HashMap<Integer, PointType>() : this.getMeasurements().get(measurementOrdinal).getTrails();
	}

	/**
	 * @param measurementOrdinal may specify an ordinal which is not present in the vault (earlier osd file - measurements added in the meantime)
	 * @param trailOrdinal
	 * @return null in case of unavailable measurement or trail
	 */
	public Integer getMeasurementPoint(int measurementOrdinal, int trailOrdinal) { // todo handle xml null values for points
		if (this.getMeasurements().containsKey(measurementOrdinal)) {
			return this.getMeasurements().get(measurementOrdinal).getTrails().containsKey(trailOrdinal) ? this.getMeasurements().get(measurementOrdinal).getTrails().get(trailOrdinal).value : null;
		}
		else {
			return null;
		}
	}

	/**
	 * @param settlementId may specify an ordinal which is not present in the vault (earlier osd file - measurements added in the meantime)
	 * @return empty in case of unavailable settlementId
	 */
	public HashMap<Integer, PointType> getSettlementPoints(int settlementId) {
		return this.getSettlements().containsKey(settlementId) ? new HashMap<Integer, PointType>() : this.getSettlements().get(settlementId).getTrails();
	}

	/**
	 * @param settlementId may specify an ordinal which is not present in the vault (earlier osd file - measurements added in the meantime)
	 * @param trailOrdinal
	 * @return null in case of unavailable settlement or trail
	 */
	public Integer getSettlementPoint(int settlementId, int trailOrdinal) {
		if (this.getSettlements().containsKey(settlementId)) {
			return this.getSettlements().get(settlementId).getTrails().containsKey(trailOrdinal) ? this.getSettlements().get(settlementId).getTrails().get(trailOrdinal).value : null;
		}
		else {
			return null;
		}
	}

	public HashMap<Integer, PointType> getScorePoints() {
		return this.getScores();
	}

	/**
	 * @param scoreLabelOrdinal 
	 * @return null in case of unavailable score
	 */
	public Integer getScorePoint(int scoreLabelOrdinal) {
		return this.getScores().get(scoreLabelOrdinal).getValue();
	}

	/**
	 * @return yyyy-MM-dd HH:mm:ss
	 */
	public String getStartTimeStampFormatted() {
		return StringHelper.getFormatedTime("yyyy-MM-dd HH:mm:ss", this.logStartTimestampMs); //$NON-NLS-1$
	}

	/**
	 * @return relative path (directory name) 
	 */
	public Path getVaultDirectoryPath() {
		return Paths.get(this.vaultDirectory);
	}

	public Path getVaultFileName() {
		return Paths.get(this.vaultName);
	}

	/**
	 * @return the non-validated object key or alternatively (if empty) the non-validated object directory
	 */
	public String getRectifiedObjectKey() {
		return this.logObjectKey.isEmpty() ? this.logObjectDirectory : this.logObjectKey;
	}

	/**
	 * @return the validated object key
	 */
	public Optional<String> getValidatedObjectKey() {
		return this.settings.getValidatedObjectKey(this.logObjectKey);
	}

	/**
	 * @return boolean value to verify if given object key is valid
	 */
	public boolean isValidObjectKey(final String objectKey) {
		return this.settings.getValidatedObjectKey(objectKey).isPresent();
	}

	public boolean isTruss() {
		return this.getMeasurements().isEmpty();
	}

	/**
	 * @return the log file path
	 */
	public Path getLogFileAsPath() {
		return Paths.get(this.logFilePath);
	}

	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append(this.vaultName).append(GDE.STRING_COMMA_BLANK);
		sb.append("isTruss=").append(isTruss()).append(GDE.STRING_COMMA_BLANK); //$NON-NLS-1$
		sb.append("logRecordSetOrdinal=").append(this.logRecordSetOrdinal).append(GDE.STRING_COMMA_BLANK); //$NON-NLS-1$
		sb.append("logRecordsetBaseName=").append(this.logRecordsetBaseName).append(GDE.STRING_COMMA_BLANK); //$NON-NLS-1$
		sb.append("logChannelNumber=").append(this.logChannelNumber).append(GDE.STRING_COMMA_BLANK); //$NON-NLS-1$
		sb.append("logObjectKey=").append(this.logObjectKey).append(GDE.STRING_COMMA_BLANK); //$NON-NLS-1$
		sb.append("logStartTimestampMs=").append(this.logStartTimestampMs).append(GDE.STRING_COMMA_BLANK); //$NON-NLS-1$
		sb.append(this.logFilePath).append(GDE.STRING_COMMA_BLANK);
		sb.append("vaultDirectory=").append(this.vaultDirectory); //$NON-NLS-1$
		return sb.toString();
	}

	/**
	* leverages the xml marshalling to sorted key value pairs due to TreeMap conversion.
	* leverages the xml marshalling to key value pairs.
	*/
	public static class CompartmentsTypeAdapter extends XmlAdapter<CompartmentsType, HashMap<Integer, CompartmentType>> {

		@Override
		public HashMap<Integer, CompartmentType> unmarshal(CompartmentsType values) {
			HashMap<Integer, CompartmentType> map = new HashMap<Integer, CompartmentType>();
			if (values != null) {
				for (CompartmentType value : values.compartment)
					map.put(value.id, value);
			}
			return map;
		}

		@Override
		public CompartmentsType marshal(HashMap<Integer, CompartmentType> map) {
			CompartmentsType aList = new CompartmentsType();
			aList.compartment = map == null ? new ArrayList<CompartmentType>() : new ArrayList<CompartmentType>(new TreeMap<>(map).values());
			return aList;
		}
	}

	/**
	* leverages the xml marshalling to key value pairs.
	*/
	public static class PointsTypeAdapter extends XmlAdapter<PointsType, HashMap<Integer, PointType>> {

		@Override
		public HashMap<Integer, PointType> unmarshal(PointsType values) {
			HashMap<Integer, PointType> map = new HashMap<Integer, PointType>();
			if (values != null) {
				for (PointType value : values.point)
					map.put(value.id, value);
			}
			return map;
		}

		@Override
		public PointsType marshal(HashMap<Integer, PointType> map) {
			PointsType aList = new PointsType();
			aList.point = map == null ? new ArrayList<PointType>() : new ArrayList<PointType>(map.values());
			return aList;
		}
	}

}
