//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1.5-b01-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.12.31 at 07:19:32 PM GMT+01:00 
//


package gde.device;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;

import gde.GDE;


/**
 * <p>Java class for comma_separator_types.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="comma_separator_types">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="semicolon"/>
 *     &lt;enumeration value="comma"/>
 *     &lt;enumeration value="colon "/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "comma_separator_types")
@XmlEnum
public enum CommaSeparatorTypes {

    @XmlEnumValue("semicolon")
    SEMICOLON(";"), //$NON-NLS-1$
    @XmlEnumValue("comma")
    COMMA(","), //$NON-NLS-1$
    @XmlEnumValue("colon")
    COLON(":"); //$NON-NLS-1$
    private final String value;

    CommaSeparatorTypes(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static CommaSeparatorTypes fromValue(String v) {
        for (CommaSeparatorTypes c: CommaSeparatorTypes.values()) {
            if (c.value.equals(v.trim())) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

  	public static String[] valuesAsStingArray() {
  		StringBuilder sb = new StringBuilder();
  		for (CommaSeparatorTypes element : CommaSeparatorTypes.values()) {
  			sb.append("  ").append(element.value).append(GDE.STRING_DASH);  //$NON-NLS-1$
  		}
  		return sb.toString().split(GDE.STRING_DASH);
  	}
}
