//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1.5-b01-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.01.05 at 04:30:00 PM GMT+01:00 
//


package osde.device;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.HexBinaryAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for DataBlockType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="DataBlockType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="format">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;attribute name="type" use="required" type="{}format_types" />
 *                 &lt;attribute name="size" use="required" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *                 &lt;attribute name="separator" type="{}comma_separator_types" default="semicolon" />
 *                 &lt;attribute name="ending" type="{http://www.w3.org/2001/XMLSchema}hexBinary" default="0a0d" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="checkSum" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;attribute name="format" type="{}format_types" default="BINARY" />
 *                 &lt;attribute name="type" type="{}checksum_types" default="XOR" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="preferredDataLocation" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="preferredFileExtention" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DataBlockType", propOrder = {
    "format",
    "checkSum",
    "preferredDataLocation",
    "preferredFileExtention"
})
public class DataBlockType {

    @XmlElement(required = true)
    protected DataBlockType.Format format;
    protected DataBlockType.CheckSum checkSum;
    protected String preferredDataLocation;
    @XmlElement(defaultValue = "*.csv")
    protected String preferredFileExtention;

    /**
     * Gets the value of the format property.
     * 
     * @return
     *     possible object is
     *     {@link DataBlockType.Format }
     *     
     */
    public DataBlockType.Format getFormat() {
        return format;
    }

    /**
     * Sets the value of the format property.
     * 
     * @param value
     *     allowed object is
     *     {@link DataBlockType.Format }
     *     
     */
    public void setFormat(DataBlockType.Format value) {
        this.format = value;
    }

    /**
     * Gets the value of the checkSum property.
     * 
     * @return
     *     possible object is
     *     {@link DataBlockType.CheckSum }
     *     
     */
    public DataBlockType.CheckSum getCheckSum() {
        return checkSum;
    }

    /**
     * Sets the value of the checkSum property.
     * 
     * @param value
     *     allowed object is
     *     {@link DataBlockType.CheckSum }
     *     
     */
    public void setCheckSum(DataBlockType.CheckSum value) {
        this.checkSum = value;
    }

    /**
     * Gets the value of the preferredDataLocation property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPreferredDataLocation() {
        return preferredDataLocation;
    }

    /**
     * Sets the value of the preferredDataLocation property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPreferredDataLocation(String value) {
        this.preferredDataLocation = value;
    }

    /**
     * Gets the value of the preferredFileExtention property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPreferredFileExtention() {
      if (preferredFileExtention == null) {
        return "*.csv";
      }
      return preferredFileExtention;
    }

    /**
     * Sets the value of the preferredFileExtention property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPreferredFileExtention(String value) {
      this.preferredFileExtention = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;attribute name="format" type="{}format_types" default="BINARY" />
     *       &lt;attribute name="type" type="{}checksum_types" default="XOR" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class CheckSum {

        @XmlAttribute
        protected FormatTypes format;
        @XmlAttribute
        protected CheckSumTypes type;

        /**
         * Gets the value of the format property.
         * 
         * @return
         *     possible object is
         *     {@link FormatTypes }
         *     
         */
        public FormatTypes getFormat() {
            if (format == null) {
                return FormatTypes.BINARY;
            }
            return format;
        }

        /**
         * Sets the value of the format property.
         * 
         * @param value
         *     allowed object is
         *     {@link FormatTypes }
         *     
         */
        public void setFormat(FormatTypes value) {
            this.format = value;
        }

        /**
         * Gets the value of the type property.
         * 
         * @return
         *     possible object is
         *     {@link CheckSumTypes }
         *     
         */
        public CheckSumTypes getType() {
            if (type == null) {
                return CheckSumTypes.XOR;
            }
            return type;
        }

        /**
         * Sets the value of the type property.
         * 
         * @param value
         *     allowed object is
         *     {@link CheckSumTypes }
         *     
         */
        public void setType(CheckSumTypes value) {
            this.type = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;attribute name="type" use="required" type="{}format_types" />
     *       &lt;attribute name="size" use="required" type="{http://www.w3.org/2001/XMLSchema}integer" />
     *       &lt;attribute name="separator" type="{}comma_separator_types" default="semicolon" />
     *       &lt;attribute name="ending" type="{http://www.w3.org/2001/XMLSchema}hexBinary" default="0a0d" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class Format {

        @XmlAttribute(required = true)
        protected FormatTypes type;
        @XmlAttribute(required = true)
        protected Integer size;
        @XmlAttribute
        protected CommaSeparatorTypes separator;
        @XmlAttribute
        @XmlJavaTypeAdapter(HexBinaryAdapter.class)
        @XmlSchemaType(name = "hexBinary")
        protected byte[] ending;

        /**
         * Gets the value of the type property.
         * 
         * @return
         *     possible object is
         *     {@link FormatTypes }
         *     
         */
        public FormatTypes getType() {
            return type;
        }

        /**
         * Sets the value of the type property.
         * 
         * @param value
         *     allowed object is
         *     {@link FormatTypes }
         *     
         */
        public void setType(FormatTypes value) {
            this.type = value;
        }

        /**
         * Gets the value of the size property.
         * 
         * @return
         *     possible object is
         *     {@link BigInteger }
         *     
         */
        public Integer getSize() {
            return size;
        }

        /**
         * Sets the value of the size property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigInteger }
         *     
         */
        public void setSize(Integer value) {
            this.size = value;
        }

        /**
         * Gets the value of the separator property.
         * 
         * @return
         *     possible object is
         *     {@link CommaSeparatorTypes }
         *     
         */
        public CommaSeparatorTypes getSeparator() {
            if (separator == null) {
                return CommaSeparatorTypes.SEMICOLON;
            }
            return separator;
        }

        /**
         * Sets the value of the separator property.
         * 
         * @param value
         *     allowed object is
         *     {@link CommaSeparatorTypes }
         *     
         */
        public void setSeparator(CommaSeparatorTypes value) {
            this.separator = value;
        }

        /**
         * Gets the value of the ending property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public byte[] getEnding() {
            if (ending == null) {
                return new HexBinaryAdapter().unmarshal("0D0A");
            }    
            return ending;
        }

        /**
         * Sets the value of the ending property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setEnding(byte[] value) {
            this.ending = (value);
        }

    }

}
