//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1.5-b01-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.01.23 at 11:34:32 AM GMT+01:00 
//


package osde.device;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;

import osde.OSDE;


/**
 * <p>Java class for data_bits_types.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="data_bits_types">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="DATABITS_5"/>
 *     &lt;enumeration value="DATABITS_6"/>
 *     &lt;enumeration value="DATABITS_7"/>
 *     &lt;enumeration value="DATABITS_8"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "data_bits_types")
@XmlEnum
public enum DataBitsTypes {

    DATABITS_5,
    DATABITS_6,
    DATABITS_7,
    DATABITS_8;

    public String value() {
        return name();
    }

    public static DataBitsTypes fromValue(String v) {
        return valueOf(v);
    }

  	public static String[] valuesAsStingArray() {
  		StringBuilder sb = new StringBuilder();
  		for (DataBitsTypes element : DataBitsTypes.values()) {
  			sb.append(element).append(OSDE.STRING_DASH);
  		}
  		return sb.toString().split(OSDE.STRING_DASH);
  	}
}
