//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1.5-b01-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.01.04 at 08:16:55 AM MEZ 
//


package gde.device;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for delta_basis_types.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="delta_basis_types">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="reference"/>
 *     &lt;enumeration value="recovery"/>
 *     &lt;enumeration value="bothAvg"/>
 *     &lt;enumeration value="inner"/>
 *     &lt;enumeration value="outer"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "delta_basis_types")
@XmlEnum
public enum DeltaBasisTypes {

    @XmlEnumValue("reference")
    REFERENCE("reference"),
    @XmlEnumValue("recovery")
    RECOVERY("recovery"),
    @XmlEnumValue("bothAvg")
    BOTH_AVG("bothAvg"),
    @XmlEnumValue("inner")
    INNER("inner"),
    @XmlEnumValue("outer")
    OUTER("outer");
    private final String value;

    DeltaBasisTypes(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static DeltaBasisTypes fromValue(String v) {
        for (DeltaBasisTypes c: DeltaBasisTypes.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
