//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1.5-b01-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.11.13 at 07:00:40 PM MEZ 
//


package gde.device;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for DevicePropertiesType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="DevicePropertiesType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Device" type="{}DeviceType"/>
 *         &lt;element name="SerialPort" type="{}SerialPortType" minOccurs="0"/>
 *         &lt;element name="TimeBase" type="{}TimeBaseType"/>
 *         &lt;element name="DataBlock" type="{}DataBlockType" minOccurs="0"/>
 *         &lt;element name="State" type="{}StateType" minOccurs="0"/>
 *         &lt;element name="Channel" type="{}ChannelType" maxOccurs="unbounded"/>
 *         &lt;element name="Desktop" type="{}DesktopType"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DevicePropertiesType", propOrder = { //$NON-NLS-1$
    "device", //$NON-NLS-1$
    "serialPort", //$NON-NLS-1$
    "timeBase", //$NON-NLS-1$
    "dataBlock", //$NON-NLS-1$
    "state", //$NON-NLS-1$
    "channel", //$NON-NLS-1$
    "desktop" //$NON-NLS-1$
})
public class DevicePropertiesType {

    @XmlElement(name = "Device", required = true) //$NON-NLS-1$
    protected DeviceType device;
    @XmlElement(name = "SerialPort") //$NON-NLS-1$
    protected SerialPortType serialPort;
    @XmlElement(name = "TimeBase", required = true) //$NON-NLS-1$
    protected TimeBaseType timeBase;
    @XmlElement(name = "DataBlock") //$NON-NLS-1$
    protected DataBlockType dataBlock;
    @XmlElement(name = "State") //$NON-NLS-1$
    protected StateType state;
    @XmlElement(name = "Channel", required = true) //$NON-NLS-1$
    protected List<ChannelType> channel;
    @XmlElement(name = "Desktop", required = true) //$NON-NLS-1$
    protected DesktopType desktop;

    /**
     * Gets the value of the device property.
     * 
     * @return
     *     possible object is
     *     {@link DeviceType }
     *     
     */
    public DeviceType getDevice() {
        return this.device;
    }

    /**
     * Sets the value of the device property.
     * 
     * @param value
     *     allowed object is
     *     {@link DeviceType }
     *     
     */
    public void setDevice(DeviceType value) {
        this.device = value;
    }

    /**
     * Gets the value of the serialPort property.
     * 
     * @return
     *     possible object is
     *     {@link SerialPortType }
     *     
     */
    public SerialPortType getSerialPort() {
        return this.serialPort;
    }

    /**
     * Sets the value of the serialPort property.
     * 
     * @param value
     *     allowed object is
     *     {@link SerialPortType }
     *     
     */
    public void setSerialPort(SerialPortType value) {
        this.serialPort = value;
    }

    /**
     * Gets the value of the timeBase property.
     * 
     * @return
     *     possible object is
     *     {@link TimeBaseType }
     *     
     */
    public TimeBaseType getTimeBase() {
        return this.timeBase;
    }

    /**
     * Sets the value of the timeBase property.
     * 
     * @param value
     *     allowed object is
     *     {@link TimeBaseType }
     *     
     */
    public void setTimeBase(TimeBaseType value) {
        this.timeBase = value;
    }

    /**
     * Gets the value of the dataBlock property.
     * 
     * @return
     *     possible object is
     *     {@link DataBlockType }
     *     
     */
    public DataBlockType getDataBlock() {
        return dataBlock;
    }

    /**
     * Sets the value of the dataBlock property.
     * 
     * @param value
     *     allowed object is
     *     {@link DataBlockType }
     *     
     */
    public void setDataBlock(DataBlockType value) {
        this.dataBlock = value;
    }

    /**
     * Gets the value of the state property.
     * 
     * @return
     *     possible object is
     *     {@link StateType }
     *     
     */
    public StateType getState() {
        return state;
    }

    /**
     * Sets the value of the state property.
     * 
     * @param value
     *     allowed object is
     *     {@link StateType }
     *     
     */
    public void setState(StateType value) {
        this.state = value;
    }

    /**
     * Gets the value of the channel property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the channel property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getChannel().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ChannelType }
     * 
     * 
     */
    public List<ChannelType> getChannel() {
        if (this.channel == null) {
        	this.channel = new ArrayList<ChannelType>();
        }
        return this.channel;
    }

    /**
     * Gets the value of the desktop property.
     * 
     * @return
     *     possible object is
     *     {@link DesktopType }
     *     
     */
    public DesktopType getDesktop() {
        return this.desktop;
    }

    /**
     * Sets the value of the desktop property.
     * 
     * @param value
     *     allowed object is
     *     {@link DesktopType }
     *     
     */
    public void setDesktop(DesktopType value) {
        this.desktop = value;
    }

}
