//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1.5-b01-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.09.17 at 08:25:21 PM CEST 
//


package gde.device;

import gde.GDE;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for flow_control_types.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="flow_control_types">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="flowcontrol_none"/>
 *     &lt;enumeration value="flowcontrol_xon_xoff"/>
 *     &lt;enumeration value="flowcontrol_hardware"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "flow_control_types")
@XmlEnum
public enum FlowControlTypes {

    @XmlEnumValue("FLOWCONTROL_NONE")
    FLOWCONTROL_NONE("FLOWCONTROL_NONE"),
    @XmlEnumValue("FLOWCONTROL_XON_XOFF")
    FLOWCONTROL_XON_XOFF("FLOWCONTROL_XON_XOFF"),
    @XmlEnumValue("FLOWCONTROL_HARDWARE")
    FLOWCONTROL_HARDWARE("FLOWCONTROL_HARDWARE");
    private final String value;

    FlowControlTypes(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static FlowControlTypes fromValue(String v) {
        for (FlowControlTypes c: FlowControlTypes.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

  	public static String[] valuesAsStingArray() {
  		StringBuilder sb = new StringBuilder();
  		for (FlowControlTypes element : FlowControlTypes.values()) {
  			sb.append(element).append(GDE.STRING_DASH);
  		}
  		return sb.toString().split(GDE.STRING_DASH);
  	}
}
