//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1.5-b01-fcs
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2012.04.01 at 10:05:45 AM CEST
//


package gde.device;

import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;

import gde.GDE;
import gde.messages.MessageIds;
import gde.messages.Messages;


/**
 * <p>Java class for input_types.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="input_types">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="FILE_IO"/>
 *     &lt;enumeration value="SERIAL_IO"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 *
 */
@XmlType(name = "input_types")
@XmlEnum
public enum InputTypes {

		FILE_IO(MessageIds.GDE_MSGT0956), //
		SERIAL_IO(MessageIds.GDE_MSGT0955);

		private String messageId;

		private InputTypes(String messageId) {
			this.messageId = messageId;
		}

		public String value() {
        return name();
    }

		public String displayText() {
			return Messages.getString(this.messageId);
		}

    public static InputTypes fromValue(String v) {
        return valueOf(v);
    }

  	public static String[] valuesAsStingArray() {
  		StringBuilder sb = new StringBuilder();
  		for (InputTypes element : InputTypes.values()) {
  			sb.append(element).append(GDE.STRING_DASH);
  		}
  		return sb.toString().split(GDE.STRING_DASH);
  	}

  	public static List<InputTypes> fromStringArray(String[] values) {
  		List<InputTypes> inputTypes = new ArrayList<InputTypes>();
  		for (String value : values) {
				inputTypes.add(InputTypes.valueOf(value));
			}
  		return inputTypes;
  	}
}
