//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1.5-b01-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.11.13 at 07:00:40 PM MEZ 
//


package osde.device;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for parity_type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="parity_types">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="PARITY_NONE"/>
 *     &lt;enumeration value="PARITY_ODD"/>
 *     &lt;enumeration value="PARITY_EVEN"/>
 *     &lt;enumeration value="PARITY_MARK"/>
 *     &lt;enumeration value="PARITY_SPACE"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "parity_types") //$NON-NLS-1$
@XmlEnum
public enum ParityTypes {

    PARITY_NONE,
    PARITY_ODD,
    PARITY_EVEN,
    PARITY_MARK,
    PARITY_SPACE;

    public String value() {
        return name();
    }

    public static ParityTypes fromValue(String v) {
        return valueOf(v);
    }

}
