//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1.5-b01-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.01.18 at 06:46:54 PM GMT+01:00 
//


package osde.device;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;

import osde.OSDE;


/**
 * <p>Java class for time_unit_types.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="time_unit_types">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="msec"/>
 *     &lt;enumeration value="sec"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "time_unit_types")
@XmlEnum
public enum TimeUnitTypes {

    @XmlEnumValue("msec")
    MSEC("msec"),
    @XmlEnumValue("sec")
    SEC("sec");
    private final String value;

    TimeUnitTypes(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static TimeUnitTypes fromValue(String v) {
        for (TimeUnitTypes c: TimeUnitTypes.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

  	public static String[] valuesAsStingArray() {
  		StringBuilder sb = new StringBuilder();
  		for (TimeUnitTypes element : TimeUnitTypes.values()) {
  			sb.append(element.value).append(OSDE.STRING_SEMICOLON);
  		}
  		return sb.toString().split(OSDE.STRING_SEMICOLON);
  	}
}
