/**************************************************************************************
  	This file is part of OpenSerialDataExplorer.

    OpenSerialDataExplorer is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    OpenSerialDataExplorer is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with OpenSerialDataExplorer.  If not, see <http://www.gnu.org/licenses/>.
****************************************************************************************/
/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class osde_io_WindowsCreateShellLink */

#ifndef _Included_osde_io_WindowsCreateShellLink
#define _Included_osde_io_WindowsCreateShellLink
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     osde_io_WindowsCreateShellLink
 * Method:    create
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_osde_utils_WindowsHelper_createDesktopLink
  (JNIEnv *, jclass, jstring, jstring, jstring, jstring, jstring, jint, jstring);

#ifdef __cplusplus
}
#endif
#endif
