//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1.5-b01-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.04.02 at 08:29:12 PM CEST 
//

package gde.device.graupner;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlValue;

/**
 * <p>Java class for MemoryType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="MemoryType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="SetupData">
 *           &lt;complexType>
 *             &lt;simpleContent>
 *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
 *                 &lt;attribute name="Synced" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
 *                 &lt;attribute name="Changed" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
 *                 &lt;attribute name="Updated" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
 *               &lt;/extension>
 *             &lt;/simpleContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="TraceData" minOccurs="0">
 *           &lt;complexType>
 *             &lt;simpleContent>
 *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
 *                 &lt;attribute name="Synced" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
 *                 &lt;attribute name="Changed" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
 *                 &lt;attribute name="Updated" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
 *               &lt;/extension>
 *             &lt;/simpleContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="CycleData" minOccurs="0">
 *           &lt;complexType>
 *             &lt;simpleContent>
 *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
 *                 &lt;attribute name="Synced" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
 *                 &lt;attribute name="Changed" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
 *                 &lt;attribute name="Updated" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
 *               &lt;/extension>
 *             &lt;/simpleContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="StepChargeData" minOccurs="0">
 *           &lt;complexType>
 *             &lt;simpleContent>
 *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
 *                 &lt;attribute name="Synced" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
 *                 &lt;attribute name="Changed" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
 *                 &lt;attribute name="Updated" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
 *               &lt;/extension>
 *             &lt;/simpleContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *       &lt;attribute name="Name" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="Synced" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
 *       &lt;attribute name="Changed" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
 *       &lt;attribute name="Updated" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "MemoryType", propOrder = { "setupData", "traceData", "cycleData", "stepChargeData" })
public class MemoryType {

	@XmlElement(name = "SetupData", required = true)
	protected MemoryType.SetupData			setupData;
	@XmlElement(name = "TraceData")
	protected MemoryType.TraceData			traceData;
	@XmlElement(name = "CycleData")
	protected MemoryType.CycleData			cycleData;
	@XmlElement(name = "StepChargeData")
	protected MemoryType.StepChargeData	stepChargeData;
	@XmlAttribute(name = "Name", required = true)
	protected String										name;
	@XmlAttribute(name = "Synced")
	protected Boolean										synced;
	@XmlAttribute(name = "Changed")
	protected Boolean										changed;
	@XmlAttribute(name = "Updated")
	protected Boolean										updated;

	/**
	 * Gets the value of the setupData property.
	 * 
	 * @return
	 *     possible object is
	 *     {@link MemoryType.SetupData }
	 *     
	 */
	public MemoryType.SetupData getSetupData() {
		return this.setupData;
	}

	/**
	 * Sets the value of the setupData property.
	 * 
	 * @param value
	 *     allowed object is
	 *     {@link MemoryType.SetupData }
	 *     
	 */
	public void setSetupData(MemoryType.SetupData value) {
		this.setupData = value;
	}

	/**
	 * Gets the value of the traceData property.
	 * 
	 * @return
	 *     possible object is
	 *     {@link MemoryType.TraceData }
	 *     
	 */
	public MemoryType.TraceData getTraceData() {
		return this.traceData;
	}

	/**
	 * Sets the value of the traceData property.
	 * 
	 * @param value
	 *     allowed object is
	 *     {@link MemoryType.TraceData }
	 *     
	 */
	public void setTraceData(MemoryType.TraceData value) {
		this.traceData = value;
	}

	/**
	 * Gets the value of the cycleData property.
	 * 
	 * @return
	 *     possible object is
	 *     {@link MemoryType.CycleData }
	 *     
	 */
	public MemoryType.CycleData getCycleData() {
		return this.cycleData;
	}

	/**
	 * Sets the value of the cycleData property.
	 * 
	 * @param value
	 *     allowed object is
	 *     {@link MemoryType.CycleData }
	 *     
	 */
	public void setCycleData(MemoryType.CycleData value) {
		this.cycleData = value;
	}

	/**
	 * Gets the value of the stepChargeData property.
	 * 
	 * @return
	 *     possible object is
	 *     {@link MemoryType.StepChargeData }
	 *     
	 */
	public MemoryType.StepChargeData getStepChargeData() {
		return this.stepChargeData;
	}

	/**
	 * Sets the value of the stepChargeData property.
	 * 
	 * @param value
	 *     allowed object is
	 *     {@link MemoryType.StepChargeData }
	 *     
	 */
	public void setStepChargeData(MemoryType.StepChargeData value) {
		this.stepChargeData = value;
	}

	/**
	 * Gets the value of the name property.
	 * 
	 * @return
	 *     possible object is
	 *     {@link String }
	 *     
	 */
	public String getName() {
		return this.name;
	}

	/**
	 * Sets the value of the name property.
	 * 
	 * @param value
	 *     allowed object is
	 *     {@link String }
	 *     
	 */
	public void setName(String value) {
		this.name = value;
	}

	/**
	 * Gets the value of the synced property.
	 * 
	 * @return
	 *     possible object is
	 *     {@link Boolean }
	 *     
	 */
	public boolean isSynced() {
		if (this.synced == null) {
			return false;
		}
		return this.synced;
	}

	/**
	 * Sets the value of the synced property.
	 * 
	 * @param value
	 *     allowed object is
	 *     {@link Boolean }
	 *     
	 */
	public void setSynced(Boolean value) {
		this.synced = value;
	}

	/**
	 * Gets the value of the changed property.
	 * 
	 * @return
	 *     possible object is
	 *     {@link Boolean }
	 *     
	 */
	public boolean isChanged() {
		if (this.changed == null) {
			return false;
		}
		return this.changed;
	}

	/**
	 * Sets the value of the changed property.
	 * 
	 * @param value
	 *     allowed object is
	 *     {@link Boolean }
	 *     
	 */
	public void setChanged(Boolean value) {
		this.changed = value;
	}

	/**
	 * Gets the value of the updated property.
	 * 
	 * @return
	 *     possible object is
	 *     {@link Boolean }
	 *     
	 */
	public boolean isUpdated() {
		if (this.updated == null) {
			return false;
		}
		return this.updated;
	}

	/**
	 * Sets the value of the updated property.
	 * 
	 * @param value
	 *     allowed object is
	 *     {@link Boolean }
	 *     
	 */
	public void setUpdated(Boolean value) {
		this.updated = value;
	}

	/**
	 * <p>Java class for anonymous complex type.
	 * 
	 * <p>The following schema fragment specifies the expected content contained within this class.
	 * 
	 * <pre>
	 * &lt;complexType>
	 *   &lt;simpleContent>
	 *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
	 *       &lt;attribute name="Synced" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
	 *       &lt;attribute name="Changed" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
	 *       &lt;attribute name="Updated" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
	 *     &lt;/extension>
	 *   &lt;/simpleContent>
	 * &lt;/complexType>
	 * </pre>
	 * 
	 * 
	 */
	@XmlAccessorType(XmlAccessType.FIELD)
	@XmlType(name = "", propOrder = { "value" })
	public static class CycleData {

		@XmlValue
		protected String	value;
		@XmlAttribute(name = "Synced")
		protected Boolean	synced;
		@XmlAttribute(name = "Changed")
		protected Boolean	changed;
		@XmlAttribute(name = "Updated")
		protected Boolean	updated;

		/**
		 * Gets the value of the value property.
		 * 
		 * @return
		 *     possible object is
		 *     {@link String }
		 *     
		 */
		public String getValue() {
			return this.value;
		}

		/**
		 * Sets the value of the value property.
		 * 
		 * @param value
		 *     allowed object is
		 *     {@link String }
		 *     
		 */
		public void setValue(String value) {
			this.value = value;
		}

		/**
		 * Gets the value of the synced property.
		 * 
		 * @return
		 *     possible object is
		 *     {@link Boolean }
		 *     
		 */
		public boolean isSynced() {
			if (this.synced == null) {
				return false;
			}
			return this.synced;
		}

		/**
		 * Sets the value of the synced property.
		 * 
		 * @param value
		 *     allowed object is
		 *     {@link Boolean }
		 *     
		 */
		public void setSynced(Boolean value) {
			this.synced = value;
		}

		/**
		 * Gets the value of the changed property.
		 * 
		 * @return
		 *     possible object is
		 *     {@link Boolean }
		 *     
		 */
		public boolean isChanged() {
			if (this.changed == null) {
				return false;
			}
			return this.changed;
		}

		/**
		 * Sets the value of the changed property.
		 * 
		 * @param value
		 *     allowed object is
		 *     {@link Boolean }
		 *     
		 */
		public void setChanged(Boolean value) {
			this.changed = value;
		}

		/**
		 * Gets the value of the updated property.
		 * 
		 * @return
		 *     possible object is
		 *     {@link Boolean }
		 *     
		 */
		public boolean isUpdated() {
			if (this.updated == null) {
				return false;
			}
			return this.updated;
		}

		/**
		 * Sets the value of the updated property.
		 * 
		 * @param value
		 *     allowed object is
		 *     {@link Boolean }
		 *     
		 */
		public void setUpdated(Boolean value) {
			this.updated = value;
		}

	}

	/**
	 * <p>Java class for anonymous complex type.
	 * 
	 * <p>The following schema fragment specifies the expected content contained within this class.
	 * 
	 * <pre>
	 * &lt;complexType>
	 *   &lt;simpleContent>
	 *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
	 *       &lt;attribute name="Synced" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
	 *       &lt;attribute name="Changed" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
	 *       &lt;attribute name="Updated" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
	 *     &lt;/extension>
	 *   &lt;/simpleContent>
	 * &lt;/complexType>
	 * </pre>
	 * 
	 * 
	 */
	@XmlAccessorType(XmlAccessType.FIELD)
	@XmlType(name = "", propOrder = { "value" })
	public static class SetupData {

		@XmlValue
		protected String	value;
		@XmlAttribute(name = "Synced")
		protected Boolean	synced;
		@XmlAttribute(name = "Changed")
		protected Boolean	changed;
		@XmlAttribute(name = "Updated")
		protected Boolean	updated;

		/**
		 * Gets the value of the value property.
		 * 
		 * @return
		 *     possible object is
		 *     {@link String }
		 *     
		 */
		public String getValue() {
			return this.value;
		}

		/**
		 * Sets the value of the value property.
		 * 
		 * @param value
		 *     allowed object is
		 *     {@link String }
		 *     
		 */
		public void setValue(String value) {
			this.value = value;
		}

		/**
		 * Gets the value of the synced property.
		 * 
		 * @return
		 *     possible object is
		 *     {@link Boolean }
		 *     
		 */
		public boolean isSynced() {
			if (this.synced == null) {
				return false;
			}
			return this.synced;
		}

		/**
		 * Sets the value of the synced property.
		 * 
		 * @param value
		 *     allowed object is
		 *     {@link Boolean }
		 *     
		 */
		public void setSynced(Boolean value) {
			this.synced = value;
		}

		/**
		 * Gets the value of the changed property.
		 * 
		 * @return
		 *     possible object is
		 *     {@link Boolean }
		 *     
		 */
		public boolean isChanged() {
			if (this.changed == null) {
				return false;
			}
			return this.changed;
		}

		/**
		 * Sets the value of the changed property.
		 * 
		 * @param value
		 *     allowed object is
		 *     {@link Boolean }
		 *     
		 */
		public void setChanged(Boolean value) {
			this.changed = value;
		}

		/**
		 * Gets the value of the updated property.
		 * 
		 * @return
		 *     possible object is
		 *     {@link Boolean }
		 *     
		 */
		public boolean isUpdated() {
			if (this.updated == null) {
				return false;
			}
			return this.updated;
		}

		/**
		 * Sets the value of the updated property.
		 * 
		 * @param value
		 *     allowed object is
		 *     {@link Boolean }
		 *     
		 */
		public void setUpdated(Boolean value) {
			this.updated = value;
		}

	}

	/**
	 * <p>Java class for anonymous complex type.
	 * 
	 * <p>The following schema fragment specifies the expected content contained within this class.
	 * 
	 * <pre>
	 * &lt;complexType>
	 *   &lt;simpleContent>
	 *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
	 *       &lt;attribute name="Synced" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
	 *       &lt;attribute name="Changed" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
	 *       &lt;attribute name="Updated" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
	 *     &lt;/extension>
	 *   &lt;/simpleContent>
	 * &lt;/complexType>
	 * </pre>
	 * 
	 * 
	 */
	@XmlAccessorType(XmlAccessType.FIELD)
	@XmlType(name = "", propOrder = { "value" })
	public static class StepChargeData {

		@XmlValue
		protected String	value;
		@XmlAttribute(name = "Synced")
		protected Boolean	synced;
		@XmlAttribute(name = "Changed")
		protected Boolean	changed;
		@XmlAttribute(name = "Updated")
		protected Boolean	updated;

		/**
		 * Gets the value of the value property.
		 * 
		 * @return
		 *     possible object is
		 *     {@link String }
		 *     
		 */
		public String getValue() {
			return this.value;
		}

		/**
		 * Sets the value of the value property.
		 * 
		 * @param value
		 *     allowed object is
		 *     {@link String }
		 *     
		 */
		public void setValue(String value) {
			this.value = value;
		}

		/**
		 * Gets the value of the synced property.
		 * 
		 * @return
		 *     possible object is
		 *     {@link Boolean }
		 *     
		 */
		public boolean isSynced() {
			if (this.synced == null) {
				return false;
			}
			return this.synced;
		}

		/**
		 * Sets the value of the synced property.
		 * 
		 * @param value
		 *     allowed object is
		 *     {@link Boolean }
		 *     
		 */
		public void setSynced(Boolean value) {
			this.synced = value;
		}

		/**
		 * Gets the value of the changed property.
		 * 
		 * @return
		 *     possible object is
		 *     {@link Boolean }
		 *     
		 */
		public boolean isChanged() {
			if (this.changed == null) {
				return false;
			}
			return this.changed;
		}

		/**
		 * Sets the value of the changed property.
		 * 
		 * @param value
		 *     allowed object is
		 *     {@link Boolean }
		 *     
		 */
		public void setChanged(Boolean value) {
			this.changed = value;
		}

		/**
		 * Gets the value of the updated property.
		 * 
		 * @return
		 *     possible object is
		 *     {@link Boolean }
		 *     
		 */
		public boolean isUpdated() {
			if (this.updated == null) {
				return false;
			}
			return this.updated;
		}

		/**
		 * Sets the value of the updated property.
		 * 
		 * @param value
		 *     allowed object is
		 *     {@link Boolean }
		 *     
		 */
		public void setUpdated(Boolean value) {
			this.updated = value;
		}

	}

	/**
	 * <p>Java class for anonymous complex type.
	 * 
	 * <p>The following schema fragment specifies the expected content contained within this class.
	 * 
	 * <pre>
	 * &lt;complexType>
	 *   &lt;simpleContent>
	 *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
	 *       &lt;attribute name="Synced" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
	 *       &lt;attribute name="Changed" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
	 *       &lt;attribute name="Updated" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
	 *     &lt;/extension>
	 *   &lt;/simpleContent>
	 * &lt;/complexType>
	 * </pre>
	 * 
	 * 
	 */
	@XmlAccessorType(XmlAccessType.FIELD)
	@XmlType(name = "", propOrder = { "value" })
	public static class TraceData {

		@XmlValue
		protected String	value;
		@XmlAttribute(name = "Synced")
		protected Boolean	synced;
		@XmlAttribute(name = "Changed")
		protected Boolean	changed;
		@XmlAttribute(name = "Updated")
		protected Boolean	updated;

		/**
		 * Gets the value of the value property.
		 * 
		 * @return
		 *     possible object is
		 *     {@link String }
		 *     
		 */
		public String getValue() {
			return this.value;
		}

		/**
		 * Sets the value of the value property.
		 * 
		 * @param value
		 *     allowed object is
		 *     {@link String }
		 *     
		 */
		public void setValue(String value) {
			this.value = value;
		}

		/**
		 * Gets the value of the synced property.
		 * 
		 * @return
		 *     possible object is
		 *     {@link Boolean }
		 *     
		 */
		public boolean isSynced() {
			if (this.synced == null) {
				return false;
			}
			return this.synced;
		}

		/**
		 * Sets the value of the synced property.
		 * 
		 * @param value
		 *     allowed object is
		 *     {@link Boolean }
		 *     
		 */
		public void setSynced(Boolean value) {
			this.synced = value;
		}

		/**
		 * Gets the value of the changed property.
		 * 
		 * @return
		 *     possible object is
		 *     {@link Boolean }
		 *     
		 */
		public boolean isChanged() {
			if (this.changed == null) {
				return false;
			}
			return this.changed;
		}

		/**
		 * Sets the value of the changed property.
		 * 
		 * @param value
		 *     allowed object is
		 *     {@link Boolean }
		 *     
		 */
		public void setChanged(Boolean value) {
			this.changed = value;
		}

		/**
		 * Gets the value of the updated property.
		 * 
		 * @return
		 *     possible object is
		 *     {@link Boolean }
		 *     
		 */
		public boolean isUpdated() {
			if (this.updated == null) {
				return false;
			}
			return this.updated;
		}

		/**
		 * Sets the value of the updated property.
		 * 
		 * @param value
		 *     allowed object is
		 *     {@link Boolean }
		 *     
		 */
		public void setUpdated(Boolean value) {
			this.updated = value;
		}
	}
}
