//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1.5-b01-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.04.04 at 09:44:59 PM CEST 
//


package gde.device.graupner;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the gde.device.graupner package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: gde.device.graupner
     * 
     */
    public ObjectFactory() {
    	//default constructor is empty
    }

    /**
     * Create an instance of {@link MemoryType.CycleData }
     * 
     */
    public MemoryType.CycleData createMemoryTypeCycleData() {
        return new MemoryType.CycleData();
    }

    /**
     * Create an instance of {@link MemoryType }
     * 
     */
    public MemoryType createMemoryType() {
        return new MemoryType();
    }

    /**
     * Create an instance of {@link UltraDuoPlusType.TireHeaterData }
     * 
     */
    public UltraDuoPlusType.TireHeaterData createUltraDuoPlusTypeTireHeaterData() {
        return new UltraDuoPlusType.TireHeaterData();
    }

    /**
     * Create an instance of {@link UltraDuoPlusType.MotorRunData }
     * 
     */
    public UltraDuoPlusType.MotorRunData createUltraDuoPlusTypeMotorRunData() {
        return new UltraDuoPlusType.MotorRunData();
    }

    /**
     * Create an instance of {@link UltraDuoPlusType }
     * 
     */
    public UltraDuoPlusType createUltraDuoPlusType() {
        return new UltraDuoPlusType();
    }

    /**
     * Create an instance of {@link MemoryType.TraceData }
     * 
     */
    public MemoryType.TraceData createMemoryTypeTraceData() {
        return new MemoryType.TraceData();
    }

    /**
     * Create an instance of {@link UltraDuoPlusType.ChannelData1 }
     * 
     */
    public UltraDuoPlusType.ChannelData1 createUltraDuoPlusTypeChannelData1() {
        return new UltraDuoPlusType.ChannelData1();
    }

    /**
     * Create an instance of {@link UltraDuoPlusType.ChannelData2 }
     * 
     */
    public UltraDuoPlusType.ChannelData2 createUltraDuoPlusTypeChannelData2() {
        return new UltraDuoPlusType.ChannelData2();
    }

    /**
     * Create an instance of {@link MemoryType.SetupData }
     * 
     */
    public MemoryType.SetupData createMemoryTypeSetupData() {
        return new MemoryType.SetupData();
    }

    /**
     * Create an instance of {@link MemoryType.StepChargeData }
     * 
     */
    public MemoryType.StepChargeData createMemoryTypeStepChargeData() {
        return new MemoryType.StepChargeData();
    }

}
