//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1.5-b01-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.03.25 at 11:38:15 AM MEZ 
//

package gde.histo.cache;

import java.util.HashMap;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;

import gde.GDE;
import gde.device.TrailTypes;
import gde.histo.cache.HistoVault.PointsTypeAdapter;

/**
 * <p>Java class for compartmentType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="compartmentType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="trails" type="{}pointsType"/>
 *       &lt;/sequence>
 *       &lt;attribute name="id" use="required" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="text" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="dataType" use="required" type="{}data_types" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "compartmentType", propOrder = { "trails" })
public class CompartmentType {

	@XmlElement(required = true)
	@XmlJavaTypeAdapter(PointsTypeAdapter.class)
	protected HashMap<Integer, PointType>	trails;
	@XmlAttribute(required = true)
	protected int													id;
	@XmlAttribute(required = true)
	protected String											text;
	@XmlAttribute(required = true)
	protected DataTypes										dataType;

	@Deprecated // for ObjectFactory only
	public CompartmentType() {
	}

	public CompartmentType(int newId, String newText, DataTypes newDataType) {
		this.id = newId;
		this.text = newText;
		this.dataType = newDataType;
	}

	public void addPoint(TrailTypes newTrailType, int newValue) {
		PointType newPoint = new PointType(newTrailType.ordinal(), newTrailType.name(), newValue);
		this.getTrails().put(newTrailType.ordinal(), newPoint);
	}

	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		if (this.trails != null) {
			for (PointType dataPoint : this.trails.values()) {
				sb.append(dataPoint.getName().toLowerCase()).append(GDE.STRING_EQUAL).append(dataPoint.getValue()).append(GDE.STRING_BLANK);
			}
		}
		return sb.toString();
	}

	/**
	 * Gets the value of the trails property.
	 * 
	 * @return
	 *     possible object is
	 *     {@link PointsType }
	 *     
	 */
	public HashMap<Integer, PointType> getTrails() {
		if (this.trails == null) {
			this.trails = new HashMap<Integer, PointType>();
		}
		return this.trails;
	}

	/**
	 * Sets the value of the trails property.
	 * 
	 * @param value
	 *     allowed object is
	 *     {@link PointsType }
	 *     
	 */
	public void setTrails(HashMap<Integer, PointType> value) {
		this.trails = value;
	}

	/**
	 * Gets the value of the id property.
	 * 
	 */
	public int getId() {
		return id;
	}

	/**
	 * Sets the value of the id property.
	 * 
	 */
	public void setId(int value) {
		this.id = value;
	}

	/**
	 * Gets the value of the text property.
	 * 
	 * @return
	 *     possible object is
	 *     {@link String }
	 *     
	 */
	public String getText() {
		return text;
	}

	/**
	 * Sets the value of the text property.
	 * 
	 * @param value
	 *     allowed object is
	 *     {@link String }
	 *     
	 */
	public void setText(String value) {
		this.text = value;
	}

    /**
     * Gets the value of the dataType property.
     * 
     * @return
     *     possible object is
     *     {@link DataTypes }
     *     
     */
    public DataTypes getDataType() {
        return dataType;
    }

    /**
     * Sets the value of the dataType property.
     * 
     * @param value
     *     allowed object is
     *     {@link DataTypes }
     *     
     */
    public void setDataType(DataTypes value) {
        this.dataType = value;
    }

}
